"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Check, Download, Eye, FileDown, Loader2, Pencil, Plus, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useTranslations } from "next-intl";
import { useState } from "react";

import { AuditLogs } from "@/components/audit/audit-logs";
import { useAuth } from "@/components/providers/auth-provider";
import { ListHeader, StatusBadge } from "@/components/shared/page-primitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type { CompanyRow } from "@/interfaces/company";
import type { CreatePartnerPayload, CustomerReferral, Partner, PartnerAgreement, PartnerCommissionPayout, PartnerPerformance, PartnerTerritory, PartnerType, PartnerTypeDefinition } from "@/interfaces/partner";
import { useDateFormat } from "@/lib/dates";
import { getCompanies } from "@/services/companies.service";
import {
  activateAgreement, adjustPartnerPayout, calculatePartnerPayout, createAgreement,
  createPartner, createPartnerType, createReferral, createTerritory, deletePartnerType,
  deleteTerritory, downloadAgreementDocument, exportPartnerReport, getAgreements,
  getPartnerPerformance, getPartnerPayouts, getPartners, getPartnerSummary,
  getPartnerTypes, getReferrals, getTerritories, renewAgreement, submitAgreement,
  terminateAgreement, transitionPartnerPayout, updatePartner, updatePartnerType,
  updateReferral, updateTerritory, viewAgreementDocument,
} from "@/services/partner.service";

export type PartnerSection = "overview" | "management" | "details" | "types" | "territories" | "customers" | "agreements" | "schemes" | "performance" | "reports" | "activity";
const SUBMODULES: Array<{ section: Exclude<PartnerSection, "overview">; number: string }> = [
  { section: "management", number: "16.2.1" }, { section: "details", number: "16.2.2" },
  { section: "types", number: "16.2.3" }, { section: "territories", number: "16.2.4" },
  { section: "customers", number: "16.2.5" }, { section: "agreements", number: "16.2.6" },
  { section: "schemes", number: "16.2.7" }, { section: "performance", number: "16.2.8" },
  { section: "reports", number: "16.2.9" }, { section: "activity", number: "16.2.10" },
];
const PARTNER_TYPES: PartnerType[] = ["INSTALLER", "DISTRIBUTOR", "REGIONAL_AGENT", "REFERRAL", "TECHNOLOGY", "CUSTOM"];
const PARTNER_STATUSES = ["ACTIVE", "INACTIVE", "SUSPENDED", "TERMINATED"] as const;
const STATES = ["JOHOR", "KEDAH", "KELANTAN", "MELAKA", "NEGERI_SEMBILAN", "PAHANG", "PENANG", "PERAK", "PERLIS", "SABAH", "SARAWAK", "SELANGOR", "TERENGGANU", "KUALA_LUMPUR", "LABUAN", "PUTRAJAYA"];

export function PartnerManagementWorkspace({ section = "overview" }: { section?: PartnerSection }) {
  const t = useTranslations("adminPartnerManagement");
  if (section === "activity") return <AuditLogs fixedCategory="PARTNER" title={t("section.activity.title")} subtitle={t("section.activity.subtitle")} />;
  if (section === "overview") return <Overview />;
  return <div className="flex h-[calc(100dvh-5rem)] flex-col gap-4"><ListHeader title={t(`section.${section}.title`)} subtitle={t(`section.${section}.subtitle`)} />
    {section === "management" && <PartnerPanel detailed={false} />}
    {section === "details" && <PartnerPanel detailed />}
    {section === "types" && <TypePanel />}
    {section === "territories" && <TerritoryPanel />}
    {section === "customers" && <CustomerPanel />}
    {section === "agreements" && <AgreementPanel />}
    {section === "schemes" && <CommissionPanel />}
    {section === "performance" && <PerformancePanel />}
    {section === "reports" && <ReportPanel />}
  </div>;
}

function Overview() {
  const t = useTranslations("adminPartnerManagement");
  const summary = useQuery({ queryKey: ["partner-summary"], queryFn: getPartnerSummary });
  return <div className="flex h-[calc(100dvh-5rem)] flex-col gap-4"><ListHeader title={t("title")} subtitle={t("subtitle")} />
    <div className="grid border-y bg-card sm:grid-cols-2 xl:grid-cols-4">{[["partners", summary.data?.total_partners ?? 0], ["customers", summary.data?.total_customers_referred ?? 0], ["active", summary.data?.by_status?.ACTIVE ?? 0], ["paid", `RM ${summary.data?.total_commission_paid ?? "0.00"}`]].map(([key, value]) => <div key={key} className="border-b border-r px-5 py-4"><p className="text-xs text-muted-foreground">{t(`metric.${key}`)}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>)}</div>
    <div className="min-h-0 flex-1 overflow-auto border-y bg-card"><div className="grid md:grid-cols-2 xl:grid-cols-3">{SUBMODULES.map((item) => <Link key={item.section} href={`/partners/${item.section}`} className="flex min-h-20 items-center gap-3 border-b border-r px-5 py-4 hover:bg-muted/40"><span className="flex-1 font-medium">{t(`section.${item.section}.title`)}</span><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link>)}</div></div>
  </div>;
}

function Panel({ loading, error, children }: { loading: boolean; error: boolean; children: React.ReactNode }) {
  const t = useTranslations("adminPartnerManagement");
  if (loading) return <div className="flex min-h-48 flex-1 items-center justify-center rounded-lg border bg-card shadow-sm"><Loader2 className="mr-2 animate-spin" />{t("loading")}</div>;
  if (error) return <div className="rounded-lg border border-destructive/25 bg-destructive/5 p-5 text-destructive">{t("loadError")}</div>;
  return <div className="min-h-0 flex-1 overflow-auto rounded-lg border bg-card shadow-sm">{children}</div>;
}

function PartnerPanel({ detailed }: { detailed: boolean }) {
  const t = useTranslations("adminPartnerManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const manage = can("partner.manage");
  const rows = useQuery({ queryKey: ["partners", detailed], queryFn: () => getPartners({ page_size: 200, sort_by: "name" }) });
  const [editing, setEditing] = useState<Partner | null | undefined>(undefined); const [statusRow, setStatusRow] = useState<Partner | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}>{manage && <div className="flex justify-end border-b p-3"><Button onClick={() => setEditing(null)}><Plus />{t("action.addPartner")}</Button></div>}
    <Table><TableHeader><TableRow>{(detailed ? ["code", "name", "company", "contact", "email", "registration", "type", "start", "end", "status", "actions"] : ["code", "name", "type", "contact", "customers", "start", "status", "actions"]).map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.code}</TableCell><TableCell>{row.name}</TableCell>{detailed && <TableCell>{row.company_name || "-"}</TableCell>}<TableCell>{row.contact_person}<p className="text-xs text-muted-foreground">{row.contact_phone}</p></TableCell>{detailed && <><TableCell>{row.contact_email}</TableCell><TableCell>{(row as Partner & { registration_number?: string }).registration_number || "-"}</TableCell></>}<TableCell>{t(`partnerType.${row.type}`)}{row.custom_type ? ` / ${row.custom_type}` : ""}</TableCell>{!detailed && <TableCell>{row.customers_referred}</TableCell>}<TableCell>{df.date(row.partnership_start)}</TableCell>{detailed && <TableCell>{df.date(row.partnership_end) || "-"}</TableCell>}<TableCell><StatusBadge label={t(`partnerStatus.${row.status}`)} tone={row.status === "ACTIVE" ? "positive" : row.status === "TERMINATED" ? "danger" : "warning"} /></TableCell><TableCell>{manage && <div className="flex gap-1"><Button size="icon-sm" variant="ghost" title={t("action.edit")} onClick={() => setEditing(row)}><Pencil /></Button><Button size="sm" variant="outline" onClick={() => setStatusRow(row)}>{t("action.status")}</Button></div>}</TableCell></TableRow>)}</TableBody></Table>
    {editing !== undefined && <PartnerDialog row={editing} onClose={() => setEditing(undefined)} onSaved={() => qc.invalidateQueries({ queryKey: ["partners"] })} />}
    {statusRow && <PartnerStatusDialog row={statusRow} onClose={() => setStatusRow(null)} onSaved={() => qc.invalidateQueries({ queryKey: ["partners"] })} />}
  </Panel>;
}

function PartnerDialog({ row, onClose, onSaved }: { row: Partner | null; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminPartnerManagement"); const types = useQuery({ queryKey: ["partner-types"], queryFn: getPartnerTypes });
  const [form, setForm] = useState<CreatePartnerPayload>({ name: row?.name ?? "", company_name: row?.company_name ?? "", type: row?.type ?? "INSTALLER", custom_type: row?.custom_type ?? "", contact_person: row?.contact_person ?? "", contact_phone: row?.contact_phone ?? "", contact_email: row?.contact_email ?? "", address: (row as Partner & { address?: string })?.address ?? "", registration_number: (row as Partner & { registration_number?: string })?.registration_number ?? "", partnership_start: row?.partnership_start ?? "", partnership_end: row?.partnership_end ?? "", notes: (row as Partner & { notes?: string })?.notes ?? "" });
  const set = (key: keyof CreatePartnerPayload, value: string) => setForm((x) => ({ ...x, [key]: value }));
  const save = useMutation({ mutationFn: () => { const payload = { ...form, partnership_end: form.partnership_end || null }; return row ? updatePartner(row.id, payload) : createPartner(payload); }, onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>{row ? t("action.editPartner") : t("action.addPartner")}</DialogTitle><DialogDescription>{t("dialog.partner")}</DialogDescription></DialogHeader><div className="grid max-h-[65dvh] gap-3 overflow-auto sm:grid-cols-2"><Input placeholder={t("field.name")} value={form.name} onChange={(e) => set("name", e.target.value)} /><Input placeholder={t("field.companyName")} value={form.company_name} onChange={(e) => set("company_name", e.target.value)} /><select className="h-8 rounded-md border bg-background px-2" value={form.type} onChange={(e) => set("type", e.target.value)}>{PARTNER_TYPES.map((x) => <option key={x} value={x}>{t(`partnerType.${x}`)}</option>)}</select>{form.type === "CUSTOM" && <select className="h-8 rounded-md border bg-background px-2" value={form.custom_type} onChange={(e) => set("custom_type", e.target.value)}><option value="">{t("field.customType")}</option>{(types.data?.results ?? []).filter((x) => !x.is_system && x.is_active).map((x) => <option key={x.id} value={x.code}>{x.name}</option>)}</select>}<Input placeholder={t("field.contactPerson")} value={form.contact_person} onChange={(e) => set("contact_person", e.target.value)} /><Input placeholder={t("field.phone")} value={form.contact_phone} onChange={(e) => set("contact_phone", e.target.value)} /><Input type="email" placeholder={t("field.email")} value={form.contact_email} onChange={(e) => set("contact_email", e.target.value)} /><Input placeholder={t("field.registration")} value={form.registration_number} onChange={(e) => set("registration_number", e.target.value)} /><Input type="date" value={form.partnership_start} onChange={(e) => set("partnership_start", e.target.value)} /><Input type="date" value={form.partnership_end ?? ""} onChange={(e) => set("partnership_end", e.target.value)} /><Textarea className="sm:col-span-2" placeholder={t("field.address")} value={form.address} onChange={(e) => set("address", e.target.value)} /><Textarea className="sm:col-span-2" placeholder={t("field.notes")} value={form.notes} onChange={(e) => set("notes", e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.name || !form.contact_person || !form.contact_phone || !form.contact_email || !form.partnership_start || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function PartnerStatusDialog({ row, onClose, onSaved }: { row: Partner; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminPartnerManagement"); const [status, setStatus] = useState(row.status); const [reason, setReason] = useState("");
  const save = useMutation({ mutationFn: () => import("@/services/api-client").then(({ api }) => api.post(`/api/partners/change-status/${row.id}/`, { status, reason })), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.status")}</DialogTitle><DialogDescription>{row.code} / {row.name}</DialogDescription></DialogHeader><select className="h-8 rounded-md border bg-background px-2" value={status} onChange={(e) => setStatus(e.target.value as Partner["status"])}>{PARTNER_STATUSES.map((x) => <option key={x} value={x}>{t(`partnerStatus.${x}`)}</option>)}</select>{(status === "SUSPENDED" || status === "TERMINATED") && <Textarea placeholder={t("field.reason")} value={reason} onChange={(e) => setReason(e.target.value)} />}<DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={save.isPending || ((status === "SUSPENDED" || status === "TERMINATED") && !reason.trim())} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

function TypePanel() {
  const t = useTranslations("adminPartnerManagement"); const qc = useQueryClient(); const { can } = useAuth(); const manage = can("partner.manage"); const rows = useQuery({ queryKey: ["partner-types"], queryFn: getPartnerTypes }); const [editing, setEditing] = useState<PartnerTypeDefinition | null | undefined>(undefined);
  const remove = useMutation({ mutationFn: deletePartnerType, onSuccess: () => qc.invalidateQueries({ queryKey: ["partner-types"] }) });
  return <Panel loading={rows.isLoading} error={rows.isError}>{manage && <div className="flex justify-end border-b p-3"><Button onClick={() => setEditing(null)}><Plus />{t("action.addType")}</Button></div>}<Table><TableHeader><TableRow>{["code", "name", "description", "source", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.code}</TableCell><TableCell>{row.name}</TableCell><TableCell>{row.description || "-"}</TableCell><TableCell>{t(row.is_system ? "status.system" : "status.custom")}</TableCell><TableCell><StatusBadge label={t(row.is_active ? "status.active" : "status.inactive")} tone={row.is_active ? "positive" : "neutral"} /></TableCell><TableCell>{manage && <div className="flex gap-1"><Button size="icon-sm" variant="ghost" onClick={() => setEditing(row)}><Pencil /></Button>{!row.is_system && <Button size="icon-sm" variant="ghost" disabled={remove.isPending} onClick={() => remove.mutate(row.id)}><Trash2 /></Button>}</div>}</TableCell></TableRow>)}</TableBody></Table>{editing !== undefined && <TypeDialog row={editing} onClose={() => setEditing(undefined)} onSaved={() => qc.invalidateQueries({ queryKey: ["partner-types"] })} />}</Panel>;
}

function TypeDialog({ row, onClose, onSaved }: { row: PartnerTypeDefinition | null; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminPartnerManagement"); const [code, setCode] = useState(row?.code ?? ""); const [name, setName] = useState(row?.name ?? ""); const [description, setDescription] = useState(row?.description ?? ""); const [active, setActive] = useState(row?.is_active ?? true);
  const save = useMutation({ mutationFn: () => row ? updatePartnerType(row.id, { name, description, is_active: active }) : createPartnerType({ code, name, description }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{row ? t("action.editType") : t("action.addType")}</DialogTitle><DialogDescription>{t("dialog.type")}</DialogDescription></DialogHeader><Input disabled={Boolean(row)} placeholder={t("field.code")} value={code} onChange={(e) => setCode(e.target.value)} /><Input placeholder={t("field.name")} value={name} onChange={(e) => setName(e.target.value)} /><Textarea placeholder={t("field.description")} value={description} onChange={(e) => setDescription(e.target.value)} />{row && <label className="flex items-center gap-2"><Switch checked={active} onCheckedChange={setActive} />{t("status.active")}</label>}<DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!code || !name || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function TerritoryPanel() {
  const t = useTranslations("adminPartnerManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const manage = can("partner.manage"); const rows = useQuery({ queryKey: ["partner-territories"], queryFn: () => getTerritories({ page_size: 200 }) }); const [editing, setEditing] = useState<PartnerTerritory | null | undefined>(undefined); const remove = useMutation({ mutationFn: deleteTerritory, onSuccess: () => qc.invalidateQueries({ queryKey: ["partner-territories"] }) });
  return <Panel loading={rows.isLoading} error={rows.isError}>{manage && <div className="flex justify-end border-b p-3"><Button onClick={() => setEditing(null)}><Plus />{t("action.addTerritory")}</Button></div>}<Table><TableHeader><TableRow>{["partner", "name", "scope", "states", "cities", "exclusive", "start", "end", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.partner.code}<p className="text-xs text-muted-foreground">{row.partner.name}</p></TableCell><TableCell>{row.name}</TableCell><TableCell>{row.is_national ? t("scope.national") : t("scope.regional")}</TableCell><TableCell>{row.states.join(", ") || "-"}</TableCell><TableCell>{[...row.cities, ...row.areas].join(", ") || "-"}</TableCell><TableCell>{row.is_exclusive ? t("status.yes") : t("status.no")}</TableCell><TableCell>{df.date(row.effective_from)}</TableCell><TableCell>{df.date(row.effective_to) || "-"}</TableCell><TableCell>{manage && <div className="flex gap-1"><Button size="icon-sm" variant="ghost" onClick={() => setEditing(row)}><Pencil /></Button><Button size="icon-sm" variant="ghost" onClick={() => remove.mutate(row.id)}><Trash2 /></Button></div>}</TableCell></TableRow>)}</TableBody></Table>{editing !== undefined && <TerritoryDialog row={editing} onClose={() => setEditing(undefined)} onSaved={() => qc.invalidateQueries({ queryKey: ["partner-territories"] })} />}</Panel>;
}

function TerritoryDialog({ row, onClose, onSaved }: { row: PartnerTerritory | null; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminPartnerManagement"); const partners = useQuery({ queryKey: ["partners", "options"], queryFn: () => getPartners({ page_size: 200, status: "ACTIVE" }) });
  const [form, setForm] = useState({ partner_id: row?.partner.id ?? "", name: row?.name ?? "", is_national: row?.is_national ?? false, states: row?.states ?? [] as string[], cities: row?.cities.join(", ") ?? "", areas: row?.areas.join(", ") ?? "", is_exclusive: row?.is_exclusive ?? false, effective_from: row?.effective_from ?? "", effective_to: row?.effective_to ?? "" }); const set = (key: string, value: unknown) => setForm((x) => ({ ...x, [key]: value }));
  const payload = () => ({ ...form, states: form.is_national ? [] : form.states, cities: form.is_national ? [] : form.cities.split(",").map((x) => x.trim()).filter(Boolean), areas: form.is_national ? [] : form.areas.split(",").map((x) => x.trim()).filter(Boolean), effective_to: form.effective_to || null });
  const save = useMutation({ mutationFn: () => row ? updateTerritory(row.id, payload()) : createTerritory(payload()), onSuccess: () => { onSaved(); onClose(); } });
  const toggleState = (state: string) => set("states", form.states.includes(state) ? form.states.filter((x) => x !== state) : [...form.states, state]);
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{row ? t("action.editTerritory") : t("action.addTerritory")}</DialogTitle><DialogDescription>{t("dialog.territory")}</DialogDescription></DialogHeader><select className="h-8 rounded-md border bg-background px-2" value={form.partner_id} onChange={(e) => set("partner_id", e.target.value)}><option value="">{t("field.selectPartner")}</option>{(partners.data?.results ?? []).map((x) => <option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</select><Input placeholder={t("field.name")} value={form.name} onChange={(e) => set("name", e.target.value)} /><label className="flex items-center gap-2"><Switch checked={form.is_national} onCheckedChange={(x) => set("is_national", x)} />{t("scope.national")}</label>{!form.is_national && <><div className="grid max-h-36 grid-cols-2 gap-1 overflow-auto border p-2 sm:grid-cols-3">{STATES.map((x) => <label key={x} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.states.includes(x)} onChange={() => toggleState(x)} />{t(`state.${x}`)}</label>)}</div><Input placeholder={t("field.citiesComma")} value={form.cities} onChange={(e) => set("cities", e.target.value)} /><Input placeholder={t("field.areasComma")} value={form.areas} onChange={(e) => set("areas", e.target.value)} /></>}<div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={form.effective_from} onChange={(e) => set("effective_from", e.target.value)} /><Input type="date" value={form.effective_to} onChange={(e) => set("effective_to", e.target.value)} /></div><label className="flex items-center gap-2"><Switch checked={form.is_exclusive} onCheckedChange={(x) => set("is_exclusive", x)} />{t("field.exclusive")}</label><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.partner_id || !form.name || !form.effective_from || (!form.is_national && !form.states.length && !form.cities && !form.areas) || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function CustomerPanel() {
  const t = useTranslations("adminPartnerManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const manage = can("partner.manage"); const rows = useQuery({ queryKey: ["partner-referrals"], queryFn: () => getReferrals({ page_size: 200 }) }); const [editing, setEditing] = useState<CustomerReferral | null | undefined>(undefined);
  return <Panel loading={rows.isLoading} error={rows.isError}>{manage && <div className="flex justify-end border-b p-3"><Button onClick={() => setEditing(null)}><Plus />{t("action.assignCustomer")}</Button></div>}<Table><TableHeader><TableRow>{["partner", "customer", "companyType", "state", "territory", "date", "eligible", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.partner.code}<p className="text-xs text-muted-foreground">{row.partner.name}</p></TableCell><TableCell>{row.company.code}<p className="text-xs text-muted-foreground">{row.company.name}</p></TableCell><TableCell>{t(`companyType.${(row.company as { type?: string }).type ?? "CONTRACTOR"}`)}</TableCell><TableCell>{t(`state.${row.state}`)}</TableCell><TableCell>{row.territory_name || "-"}</TableCell><TableCell>{df.date(row.referred_on)}</TableCell><TableCell>{row.commission_eligible ? t("status.yes") : t("status.no")}</TableCell><TableCell>{manage && <Button size="icon-sm" variant="ghost" onClick={() => setEditing(row)}><Pencil /></Button>}</TableCell></TableRow>)}</TableBody></Table>{editing !== undefined && <ReferralDialog row={editing} onClose={() => setEditing(undefined)} onSaved={() => qc.invalidateQueries({ queryKey: ["partner-referrals"] })} />}</Panel>;
}

function ReferralDialog({ row, onClose, onSaved }: { row: CustomerReferral | null; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminPartnerManagement"); const partners = useQuery({ queryKey: ["partners", "options"], queryFn: () => getPartners({ page_size: 200, status: "ACTIVE" }) }); const companies = useQuery({ queryKey: ["companies", "partner-options"], queryFn: () => getCompanies({ page_size: 200, sort_by: "name" }) }); const territories = useQuery({ queryKey: ["partner-territories", "options"], queryFn: () => getTerritories({ page_size: 200 }) });
  const [form, setForm] = useState({ partner_id: row?.partner.id ?? "", company_id: row?.company.id ?? "", territory: row?.territory ?? "", commission_eligible: row?.commission_eligible ?? true, commission_start: "", commission_end: "", notes: "", reason: "" }); const set = (key: string, value: unknown) => setForm((x) => ({ ...x, [key]: value }));
  const save = useMutation({ mutationFn: () => row ? updateReferral(row.id, form) : createReferral(form), onSuccess: () => { onSaved(); onClose(); } }); const territoryOptions = (territories.data?.results ?? []).filter((x) => x.partner.id === form.partner_id);
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{row ? t("action.editAssignment") : t("action.assignCustomer")}</DialogTitle><DialogDescription>{t("dialog.referral")}</DialogDescription></DialogHeader><select className="h-8 rounded-md border bg-background px-2" value={form.partner_id} onChange={(e) => set("partner_id", e.target.value)}><option value="">{t("field.selectPartner")}</option>{(partners.data?.results ?? []).map((x) => <option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</select><select disabled={Boolean(row)} className="h-8 rounded-md border bg-background px-2" value={form.company_id} onChange={(e) => set("company_id", e.target.value)}><option value="">{t("field.selectCustomer")}</option>{(companies.data?.results ?? []).map((x: CompanyRow) => <option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</select><select className="h-8 rounded-md border bg-background px-2" value={form.territory ?? ""} onChange={(e) => set("territory", e.target.value)}><option value="">{t("field.noTerritory")}</option>{territoryOptions.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={form.commission_start} onChange={(e) => set("commission_start", e.target.value)} /><Input type="date" value={form.commission_end} onChange={(e) => set("commission_end", e.target.value)} /></div><label className="flex items-center gap-2"><Switch checked={form.commission_eligible} onCheckedChange={(x) => set("commission_eligible", x)} />{t("field.commissionEligible")}</label><Textarea placeholder={t("field.notes")} value={form.notes} onChange={(e) => set("notes", e.target.value)} />{row && <Textarea placeholder={t("field.reason")} value={form.reason} onChange={(e) => set("reason", e.target.value)} />}<DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.partner_id || !form.company_id || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function AgreementPanel() {
  const t = useTranslations("adminPartnerManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const manage = can("partner.manage"); const rows = useQuery({ queryKey: ["partner-agreements"], queryFn: () => getAgreements({ page_size: 200 }) }); const [creating, setCreating] = useState(false); const [acting, setActing] = useState<{ row: PartnerAgreement; action: "activate" | "renew" | "terminate" } | null>(null);
  const submit = useMutation({ mutationFn: submitAgreement, onSuccess: () => qc.invalidateQueries({ queryKey: ["partner-agreements"] }) });
  return <Panel loading={rows.isLoading} error={rows.isError}>{manage && <div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.addAgreement")}</Button></div>}<Table><TableHeader><TableRow>{["agreement", "partner", "version", "effective", "expiry", "document", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.agreement_number}<p className="text-xs text-muted-foreground">{row.title}</p></TableCell><TableCell>{row.partner.code}<p className="text-xs text-muted-foreground">{row.partner.name}</p></TableCell><TableCell>v{row.version ?? 1}</TableCell><TableCell>{df.date(row.effective_from)}</TableCell><TableCell>{df.date(row.effective_to) || "-"}</TableCell><TableCell>{row.document_name ? <div className="flex gap-1"><Button size="icon-sm" variant="ghost" title={t("action.view")} onClick={() => viewAgreementDocument(row.id)}><Eye /></Button><Button size="icon-sm" variant="ghost" title={t("action.download")} onClick={() => downloadAgreementDocument(row.id)}><Download /></Button></div> : "-"}</TableCell><TableCell><StatusBadge label={t(`agreementStatus.${row.status}`)} tone={row.status === "ACTIVE" ? "positive" : row.status === "TERMINATED" || row.status === "EXPIRED" ? "danger" : "warning"} /></TableCell><TableCell>{manage && <div className="flex flex-wrap gap-1">{row.status === "DRAFT" && <Button size="sm" variant="outline" disabled={!row.document_name || submit.isPending} onClick={() => submit.mutate(row.id)}>{t("action.submit")}</Button>}{(row.status === "DRAFT" || row.status === "PENDING_SIGNATURE") && <Button size="sm" onClick={() => setActing({ row, action: "activate" })}>{t("action.activate")}</Button>}{(row.status === "ACTIVE" || row.status === "EXPIRED") && <Button size="sm" variant="outline" onClick={() => setActing({ row, action: "renew" })}>{t("action.renew")}</Button>}{(row.status === "ACTIVE" || row.status === "PENDING_SIGNATURE") && <Button size="sm" variant="destructive" onClick={() => setActing({ row, action: "terminate" })}>{t("action.terminate")}</Button>}</div>}</TableCell></TableRow>)}</TableBody></Table>{creating && <AgreementDialog onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["partner-agreements"] })} />}{acting && <AgreementActionDialog {...acting} onClose={() => setActing(null)} onSaved={() => qc.invalidateQueries({ queryKey: ["partner-agreements"] })} />}</Panel>;
}

function AgreementDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminPartnerManagement"); const partners = useQuery({ queryKey: ["partners", "options"], queryFn: () => getPartners({ page_size: 200, status: "ACTIVE" }) }); const [document, setDocument] = useState<File | null>(null); const [config, setConfig] = useState("{}"); const [form, setForm] = useState({ partner_id: "", title: "", description: "", terms: "", effective_from: "", effective_to: "", commission_basis: "FIXED_PER_CUSTOMER", commission_rate: "0", minimum_payout: "", payout_cycle: "MONTHLY" }); const set = (key: string, value: string) => setForm((x) => ({ ...x, [key]: value }));
  const save = useMutation({ mutationFn: () => createAgreement({ ...form, calculation_config: JSON.parse(config || "{}") as Record<string, unknown>, document }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>{t("action.addAgreement")}</DialogTitle><DialogDescription>{t("dialog.agreement")}</DialogDescription></DialogHeader><div className="grid max-h-[65dvh] gap-3 overflow-auto sm:grid-cols-2"><select className="h-8 rounded-md border bg-background px-2 sm:col-span-2" value={form.partner_id} onChange={(e) => set("partner_id", e.target.value)}><option value="">{t("field.selectPartner")}</option>{(partners.data?.results ?? []).map((x) => <option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</select><Input placeholder={t("field.title")} value={form.title} onChange={(e) => set("title", e.target.value)} /><Input type="file" accept=".pdf,.doc,.docx" onChange={(e) => setDocument(e.target.files?.[0] ?? null)} /><Textarea placeholder={t("field.description")} value={form.description} onChange={(e) => set("description", e.target.value)} /><Textarea placeholder={t("field.terms")} value={form.terms} onChange={(e) => set("terms", e.target.value)} /><Input type="date" value={form.effective_from} onChange={(e) => set("effective_from", e.target.value)} /><Input type="date" value={form.effective_to} onChange={(e) => set("effective_to", e.target.value)} /><select className="h-8 rounded-md border bg-background px-2" value={form.commission_basis} onChange={(e) => set("commission_basis", e.target.value)}>{["FIXED_PER_CUSTOMER", "PERCENT_OF_SAAS", "PERCENT_OF_TOTAL", "TIERED", "CUSTOM"].map((x) => <option key={x} value={x}>{t(`commissionBasis.${x}`)}</option>)}</select><Input type="number" step="0.01" placeholder={t("field.rate")} value={form.commission_rate} onChange={(e) => set("commission_rate", e.target.value)} /><Input type="number" step="0.01" placeholder={t("field.minimumPayout")} value={form.minimum_payout} onChange={(e) => set("minimum_payout", e.target.value)} /><select className="h-8 rounded-md border bg-background px-2" value={form.payout_cycle} onChange={(e) => set("payout_cycle", e.target.value)}><option value="MONTHLY">{t("cycle.MONTHLY")}</option><option value="QUARTERLY">{t("cycle.QUARTERLY")}</option></select>{(form.commission_basis === "TIERED" || form.commission_basis === "CUSTOM") && <Textarea className="font-mono text-xs sm:col-span-2" placeholder={t("field.calculationConfig")} value={config} onChange={(e) => setConfig(e.target.value)} />}</div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.partner_id || !form.title || !form.description || !form.terms || !form.effective_from || !document || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function AgreementActionDialog({ row, action, onClose, onSaved }: { row: PartnerAgreement; action: "activate" | "renew" | "terminate"; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminPartnerManagement"); const [primary, setPrimary] = useState(""); const [secondary, setSecondary] = useState(""); const save = useMutation({ mutationFn: () => action === "activate" ? activateAgreement(row.id, primary, secondary) : action === "renew" ? renewAgreement(row.id, { effective_from: primary, effective_to: secondary }) : terminateAgreement(row.id, primary), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t(`action.${action}`)}</DialogTitle><DialogDescription>{row.agreement_number} / {row.partner.name}</DialogDescription></DialogHeader>{action === "activate" && <><Input placeholder={t("field.signedBy")} value={primary} onChange={(e) => setPrimary(e.target.value)} /><Input type="date" value={secondary} onChange={(e) => setSecondary(e.target.value)} /></>}{action === "renew" && <><Input type="date" value={primary} onChange={(e) => setPrimary(e.target.value)} /><Input type="date" value={secondary} onChange={(e) => setSecondary(e.target.value)} /></>}{action === "terminate" && <Textarea placeholder={t("field.reason")} value={primary} onChange={(e) => setPrimary(e.target.value)} />}<DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!primary || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

function CommissionPanel() {
  const t = useTranslations("adminPartnerManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const manage = can("partner.manage"); const agreements = useQuery({ queryKey: ["partner-agreements", "schemes"], queryFn: () => getAgreements({ page_size: 200 }) }); const payouts = useQuery({ queryKey: ["partner-payouts"], queryFn: () => getPartnerPayouts({ page_size: 200 }) }); const [calculating, setCalculating] = useState(false); const [acting, setActing] = useState<PartnerCommissionPayout | null>(null);
  return <div className="min-h-0 flex-1 overflow-auto border-y bg-card"><div className="border-b px-5 py-3 font-medium">{t("heading.schemes")}</div><Table><TableHeader><TableRow>{["partner", "agreement", "basis", "rate", "cycle", "effective", "status"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(agreements.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.partner.name}</TableCell><TableCell>{row.agreement_number}</TableCell><TableCell>{t(`commissionBasis.${row.commission_basis}`)}</TableCell><TableCell>{row.commission_rate}</TableCell><TableCell>{t(`cycle.${row.payout_cycle ?? "MONTHLY"}`)}</TableCell><TableCell>{df.date(row.effective_from)} - {df.date(row.effective_to) || t("status.openEnded")}</TableCell><TableCell>{t(`agreementStatus.${row.status}`)}</TableCell></TableRow>)}</TableBody></Table><div className="flex items-center justify-between border-y px-5 py-3"><span className="font-medium">{t("heading.payouts")}</span>{manage && <Button onClick={() => setCalculating(true)}><Plus />{t("action.calculate")}</Button>}</div><Table><TableHeader><TableRow>{["payout", "partner", "period", "customers", "saasRevenue", "platformRevenue", "gross", "net", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(payouts.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.payout_code}</TableCell><TableCell>{row.partner.name}</TableCell><TableCell>{df.date(row.period_start)} - {df.date(row.period_end)}</TableCell><TableCell>{row.new_customers}</TableCell><TableCell>RM {row.saas_revenue}</TableCell><TableCell>RM {row.platform_commission_revenue ?? "0.00"}</TableCell><TableCell>RM {row.gross_amount}</TableCell><TableCell>RM {row.net_amount}</TableCell><TableCell><StatusBadge label={t(`payoutStatus.${row.state}`)} tone={row.state === "PAID" ? "positive" : row.state === "REJECTED" ? "danger" : "warning"} /></TableCell><TableCell>{manage && row.state !== "PAID" && <Button size="sm" variant="outline" onClick={() => setActing(row)}>{t("action.process")}</Button>}</TableCell></TableRow>)}</TableBody></Table>{calculating && <PayoutCalculationDialog onClose={() => setCalculating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["partner-payouts"] })} />}{acting && <PayoutActionDialog row={acting} onClose={() => setActing(null)} onSaved={() => qc.invalidateQueries({ queryKey: ["partner-payouts"] })} />}</div>;
}

function PayoutCalculationDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const t = useTranslations("adminPartnerManagement"); const partners = useQuery({ queryKey: ["partners", "options"], queryFn: () => getPartners({ page_size: 200, status: "ACTIVE" }) }); const [partner, setPartner] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const save = useMutation({ mutationFn: () => calculatePartnerPayout({ partner_id: partner, period_start: start, period_end: end }), onSuccess: () => { onSaved(); onClose(); } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.calculate")}</DialogTitle><DialogDescription>{t("dialog.payout")}</DialogDescription></DialogHeader><select className="h-8 rounded-md border bg-background px-2" value={partner} onChange={(e) => setPartner(e.target.value)}><option value="">{t("field.selectPartner")}</option>{(partners.data?.results ?? []).map((x) => <option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={start} onChange={(e) => setStart(e.target.value)} /><Input type="date" value={end} onChange={(e) => setEnd(e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!partner || !start || !end || save.isPending} onClick={() => save.mutate()}><Check />{t("action.calculate")}</Button></DialogFooter></DialogContent></Dialog>; }

function PayoutActionDialog({ row, onClose, onSaved }: { row: PartnerCommissionPayout; onClose: () => void; onSaved: () => void }) { const t = useTranslations("adminPartnerManagement"); const options: Record<string, string[]> = { DRAFT: ["PENDING_APPROVAL"], PENDING_APPROVAL: ["APPROVED", "REJECTED"], REJECTED: ["PENDING_APPROVAL"], APPROVED: ["PAID"] }; const [state, setState] = useState(options[row.state]?.[0] ?? ""); const [reason, setReason] = useState(""); const [reference, setReference] = useState(""); const [adjustment, setAdjustment] = useState(""); const save = useMutation({ mutationFn: async () => { if (row.state === "DRAFT" && adjustment) await adjustPartnerPayout(row.id, adjustment, reason || t("status.manualAdjustment")); return transitionPartnerPayout(row.id, state, { reason, payment_reference: reference }); }, onSuccess: () => { onSaved(); onClose(); } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.process")}</DialogTitle><DialogDescription>{row.payout_code} / RM {row.net_amount}</DialogDescription></DialogHeader><select className="h-8 rounded-md border bg-background px-2" value={state} onChange={(e) => setState(e.target.value)}>{(options[row.state] ?? []).map((x) => <option key={x} value={x}>{t(`payoutStatus.${x}`)}</option>)}</select>{row.state === "DRAFT" && <Input type="number" step="0.01" placeholder={t("field.adjustment")} value={adjustment} onChange={(e) => setAdjustment(e.target.value)} />}{state === "PAID" && <Input placeholder={t("field.paymentReference")} value={reference} onChange={(e) => setReference(e.target.value)} />}<Textarea placeholder={t("field.reason")} value={reason} onChange={(e) => setReason(e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!state || (state === "REJECTED" && !reason) || (state === "PAID" && !reference) || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>; }

function PerformancePanel() {
  const t = useTranslations("adminPartnerManagement"); const [partner, setPartner] = useState(""); const [state, setState] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const partners = useQuery({ queryKey: ["partners", "options"], queryFn: () => getPartners({ page_size: 200 }) }); const rows = useQuery({ queryKey: ["partner-performance", partner, state, from, to], queryFn: () => getPartnerPerformance({ partner, state, date_from: from, date_to: to }) });
  return <Panel loading={rows.isLoading} error={rows.isError}><div className="grid gap-2 border-b p-3 sm:grid-cols-4"><select className="h-8 rounded-md border bg-background px-2" value={partner} onChange={(e) => setPartner(e.target.value)}><option value="">{t("field.allPartners")}</option>{(partners.data?.results ?? []).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="h-8 rounded-md border bg-background px-2" value={state} onChange={(e) => setState(e.target.value)}><option value="">{t("field.allStates")}</option>{STATES.map((x) => <option key={x} value={x}>{t(`state.${x}`)}</option>)}</select><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></div><PerformanceTable rows={rows.data?.results ?? []} /></Panel>;
}

function PerformanceTable({ rows }: { rows: PartnerPerformance[] }) { const t = useTranslations("adminPartnerManagement"); return <Table><TableHeader><TableRow>{["partner", "customers", "contractors", "recyclers", "saasRevenue", "platformRevenue", "partnerCommission"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.partner_id}><TableCell>{row.partner_code}<p className="text-xs text-muted-foreground">{row.partner_name}</p></TableCell><TableCell>{row.new_customers}</TableCell><TableCell>{row.contractors}</TableCell><TableCell>{row.recyclers}</TableCell><TableCell>RM {row.saas_revenue}</TableCell><TableCell>RM {row.platform_commission_revenue}</TableCell><TableCell>RM {row.partner_commission}</TableCell></TableRow>)}</TableBody></Table>; }

function ReportPanel() { const t = useTranslations("adminPartnerManagement"); const reports = [["partners", ["code", "name", "company_name", "type", "status", "contact_person", "contact_phone", "contact_email", "customer_count"]], ["customers", ["partner", "company", "territory_name", "state", "referred_on", "commission_eligible"]], ["states", ["state", "customer_count", "contractor_count", "recycler_count"]], ["commissions", ["payout_code", "partner", "period_start", "period_end", "gross_amount", "net_amount", "state"]], ["revenue", ["payout_code", "partner", "saas_revenue", "platform_commission_revenue", "total_revenue", "net_amount"]], ["performance", ["partner_code", "partner_name", "new_customers", "contractors", "recyclers", "saas_revenue", "platform_commission_revenue", "partner_commission"]]] as const; const exporting = useMutation({ mutationFn: ({ dataset, format, fields }: { dataset: string; format: "pdf" | "xlsx"; fields: readonly string[] }) => exportPartnerReport(dataset, format, t(`report.${dataset}`), fields.map((key) => ({ key, label: t(`exportColumn.${key}`) }))) }); return <div className="min-h-0 flex-1 divide-y overflow-auto border-y bg-card">{reports.map(([dataset, fields]) => <div key={dataset} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="font-medium">{t(`report.${dataset}`)}</p><p className="text-xs text-muted-foreground">{t(`report.${dataset}Subtitle`)}</p></div><div className="flex gap-2"><Button variant="outline" disabled={exporting.isPending} onClick={() => exporting.mutate({ dataset, format: "pdf", fields })}><FileDown />PDF</Button><Button disabled={exporting.isPending} onClick={() => exporting.mutate({ dataset, format: "xlsx", fields })}><FileDown />Excel</Button></div></div>)}</div>; }
