"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Check, Download, Loader2, Pencil, Plus, RotateCcw, Save, Trash2, Wrench } from "lucide-react";
import Link from "next/link";
import { useTranslations } from "next-intl";
import { useState } from "react";

import { useAuth } from "@/components/providers/auth-provider";
import { ListHeader, StatusBadge, TypeBadge } from "@/components/shared/page-primitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type {
  Asset, AssetAssignment, AssetCategory, AssetCategoryDefinition, AssetDisposal,
  AssetInstallation, AssetMaintenance, AssetPurchase, AssetStatus,
  CreateAssetPayload, InstallationStatus, MaintenanceType,
} from "@/interfaces/asset";
import { useDateFormat } from "@/lib/dates";
import {
  completeAssetMaintenance, createAsset, createAssetAssignment, createAssetCategory,
  createAssetDisposal, createAssetInstallation, createAssetMaintenance, createAssetPurchase,
  createMovement, decideAssetDisposal, deleteAssetCategory, exportAssetReport,
  getAssetAssignments, getAssetCategories, getAssetDisposals, getAssetInstallations,
  getAssetMaintenance, getAssetOptions, getAssetPurchases, getAssetReportSummary,
  getAssets, getAssetStock, getAssetSummary, getMovements, receiveAssetPurchase,
  returnAssetAssignment, setAssetActive, startAssetMaintenance,
  transitionAssetInstallation, updateAsset, updateAssetCategory,
} from "@/services/asset.service";

export type AssetSection =
  | "overview" | "management" | "categories" | "purchases"
  | "inventory" | "assignments" | "installations" | "transfers" | "repairs"
  | "maintenance" | "disposals" | "reports";

const SUBMODULES: Array<{ section: Exclude<AssetSection, "overview">; number: string }> = [
  { section: "management", number: "17.2.1" },
  { section: "categories", number: "17.2.3" }, { section: "purchases", number: "17.2.4" },
  { section: "inventory", number: "17.2.5" }, { section: "assignments", number: "17.2.6" },
  { section: "installations", number: "17.2.7" }, { section: "transfers", number: "17.2.8" },
  { section: "repairs", number: "17.2.9" }, { section: "maintenance", number: "17.2.10" },
  { section: "disposals", number: "17.2.11" },
  { section: "reports", number: "17.2.13" },
];

const CATEGORIES: AssetCategory[] = [
  "GATEWAY", "AI_CCTV", "ANPR_CAMERA", "INDUSTRIAL_COMPUTER", "INDUSTRIAL_GATEWAY",
  "ROUTER", "SIM_CARD", "DEMO_KIT", "NOTEBOOK", "TABLET", "MOBILE_PHONE",
  "TEST_EQUIPMENT", "TOOL", "LED_DISPLAY", "BARRIER_GATE", "NETWORK_SWITCH",
  "UPS", "SERVER", "OTHER",
];
const ASSET_STATUSES: AssetStatus[] = ["IN_STOCK", "DEPLOYED", "BORROWED", "MAINTENANCE", "FAULTY", "RETIRED"];
const MAINTENANCE_TYPES: MaintenanceType[] = ["PREVENTIVE", "CORRECTIVE", "CALIBRATION", "UPGRADE", "INSPECTION"];
const statusTone = (status: string): "positive" | "info" | "warning" | "danger" | "neutral" => {
  if (["ACTIVE", "COMPLETED", "RECEIVED", "RETURNED", "IN_STOCK", "APPROVED"].includes(status)) return "positive";
  if (["REJECTED", "FAULTY", "OVERDUE", "RETIRED"].includes(status)) return "danger";
  if (["IN_PROGRESS", "PARTIALLY_RECEIVED", "MAINTENANCE", "BORROWED", "REQUESTED"].includes(status)) return "warning";
  if (["DEPLOYED", "INSTALLED", "ORDERED", "SCHEDULED"].includes(status)) return "info";
  return "neutral";
};

export function AssetManagementWorkspace({ section = "overview" }: { section?: AssetSection }) {
  const t = useTranslations("adminAssetManagement");
  if (section === "overview") return <Overview />;
  return <div className="flex h-[calc(100dvh-5rem)] flex-col gap-4">
    <ListHeader title={t(`section.${section}.title`)} subtitle={t(`section.${section}.subtitle`)} />
    {section === "management" && <AssetPanel mode="search" />}
    {section === "categories" && <CategoryPanel />}
    {section === "purchases" && <PurchasePanel />}
    {section === "inventory" && <InventoryPanel />}
    {section === "assignments" && <AssignmentPanel />}
    {section === "installations" && <InstallationPanel />}
    {section === "transfers" && <TransferPanel />}
    {section === "repairs" && <MaintenancePanel repairs />}
    {section === "maintenance" && <MaintenancePanel repairs={false} />}
    {section === "disposals" && <DisposalPanel />}
    {section === "reports" && <ReportPanel />}
  </div>;
}

function Overview() {
  const t = useTranslations("adminAssetManagement");
  const summary = useQuery({ queryKey: ["asset-summary"], queryFn: getAssetSummary });
  return <div className="flex h-[calc(100dvh-5rem)] flex-col gap-4">
    <ListHeader title={t("title")} subtitle={t("subtitle")} />
    <div className="grid overflow-hidden rounded-lg border bg-card shadow-sm sm:grid-cols-2 xl:grid-cols-4">
      {[["total", summary.data?.total_assets ?? 0], ["available", summary.data?.by_status?.IN_STOCK ?? 0], ["deployed", summary.data?.by_status?.DEPLOYED ?? 0], ["value", `RM ${summary.data?.total_value ?? "0.00"}`]].map(([key, value]) => <div key={key} className="border-b border-r px-5 py-4"><p className="text-xs text-muted-foreground">{t(`metric.${key}`)}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>)}
    </div>
    <div className="min-h-0 flex-1 overflow-auto rounded-lg border bg-card shadow-sm"><div className="grid md:grid-cols-2 xl:grid-cols-3">
      {SUBMODULES.map((item) => <Link key={item.section} href={`/assets/${item.section}`} className="flex min-h-20 items-center gap-3 border-b border-r px-5 py-4 hover:bg-muted/40"><span className="flex-1 font-medium">{t(`section.${item.section}.title`)}</span><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link>)}
    </div></div>
  </div>;
}

function Panel({ loading, error, children }: { loading: boolean; error: boolean; children: React.ReactNode }) {
  const t = useTranslations("adminAssetManagement");
  if (loading) return <div className="flex min-h-48 flex-1 items-center justify-center rounded-lg border bg-card shadow-sm"><Loader2 className="mr-2 h-4 w-4 animate-spin" />{t("loading")}</div>;
  if (error) return <div className="rounded-lg border border-destructive/25 bg-destructive/5 p-5 text-destructive">{t("loadError")}</div>;
  return <div className="min-h-0 flex-1 overflow-auto rounded-lg border bg-card shadow-sm">{children}</div>;
}

function SelectField({ value, onChange, children, className = "" }: { value: string; onChange: (value: string) => void; children: React.ReactNode; className?: string }) {
  return <select className={`h-8 rounded-md border bg-background px-2 text-sm ${className}`} value={value} onChange={(e) => onChange(e.target.value)}>{children}</select>;
}

function AssetPanel({ mode }: { mode: "management" | "details" | "search" }) {
  const t = useTranslations("adminAssetManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth();
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [status, setStatus] = useState("");
  const rows = useQuery({ queryKey: ["assets", mode, search, category, status], queryFn: () => getAssets({ page_size: 200, search: search || undefined, category: category || undefined, status: status || undefined, sort_by: "asset_code" }) });
  const [editing, setEditing] = useState<Asset | null | undefined>(undefined);
  const active = useMutation({ mutationFn: ({ row, enabled }: { row: Asset; enabled: boolean }) => setAssetActive(row.id, enabled), onSuccess: () => qc.invalidateQueries({ queryKey: ["assets"] }) });
  const detailed = mode !== "management";
  return <Panel loading={rows.isLoading} error={rows.isError}>
    <div className="flex flex-wrap items-center gap-2 border-b p-3">
      {mode === "search" && <Input className="max-w-xs" value={search} onChange={(e) => setSearch(e.target.value)} placeholder={t("field.search")} />}
      {mode === "search" && <><SelectField value={category} onChange={setCategory}><option value="">{t("field.allCategories")}</option>{CATEGORIES.map((x) => <option key={x} value={x}>{t(`category.${x}`)}</option>)}</SelectField><SelectField value={status} onChange={setStatus}><option value="">{t("field.allStatuses")}</option>{ASSET_STATUSES.map((x) => <option key={x} value={x}>{t(`assetStatus.${x}`)}</option>)}</SelectField></>}
      {mode === "management" && can("asset.manage") && <Button className="ml-auto" onClick={() => setEditing(null)}><Plus />{t("action.addAsset")}</Button>}
    </div>
    <Table><TableHeader><TableRow>{(detailed ? ["code", "name", "category", "brandModel", "serial", "purchaseDate", "warranty", "holder", "companyProject", "status", "actions"] : ["code", "name", "category", "serial", "location", "status", "active", "actions"]).map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>
      {(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.asset_code}</TableCell><TableCell>{row.name}</TableCell><TableCell><TypeBadge label={row.custom_category_name || t(`category.${row.category}`)} /></TableCell>{detailed && <TableCell>{[row.brand, row.model].filter(Boolean).join(" / ") || "-"}</TableCell>}<TableCell>{row.serial_number}</TableCell>{detailed ? <><TableCell>{df.date(row.purchase_date)}<p className="text-xs text-muted-foreground">RM {row.purchase_price}</p></TableCell><TableCell>{df.date(row.warranty_expires_on) || "-"}</TableCell><TableCell>{row.holder_name || row.department_name || row.current_warehouse || "-"}</TableCell><TableCell>{row.deployed_company_name || "-"}<p className="text-xs text-muted-foreground">{row.project_name || ""}</p></TableCell></> : <TableCell>{row.project_name || row.deployed_company_name || row.current_warehouse || row.holder_name || "-"}</TableCell>}<TableCell><StatusBadge label={t(`assetStatus.${row.status}`)} tone={statusTone(row.status)} /></TableCell>{!detailed && <TableCell><StatusBadge label={t(row.is_active ? "status.active" : "status.inactive")} tone={row.is_active ? "positive" : "neutral"} /></TableCell>}<TableCell>{can("asset.manage") && <div className="flex gap-1"><Button size="icon-sm" variant="ghost" title={t("action.edit")} onClick={() => setEditing(row)}><Pencil /></Button>{row.status !== "RETIRED" && <Button size="sm" variant="outline" disabled={active.isPending} onClick={() => active.mutate({ row, enabled: !row.is_active })}>{t(row.is_active ? "action.deactivate" : "action.activate")}</Button>}</div>}</TableCell></TableRow>)}
    </TableBody></Table>
    {editing !== undefined && <AssetDialog row={editing} onClose={() => setEditing(undefined)} onSaved={() => qc.invalidateQueries({ queryKey: ["assets"] })} />}
  </Panel>;
}

function AssetDialog({ row, onClose, onSaved }: { row: Asset | null; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement");
  const categories = useQuery({ queryKey: ["asset-categories", "options"], queryFn: () => getAssetCategories({ page_size: 200 }) });
  const [form, setForm] = useState<CreateAssetPayload>({ category: row?.category ?? "GATEWAY", custom_category: row?.custom_category ?? null, name: row?.name ?? "", brand: row?.brand ?? "", model: row?.model ?? "", serial_number: row?.serial_number ?? "", purchase_date: row?.purchase_date ?? "", purchase_price: row?.purchase_price ?? "", supplier: row?.supplier ?? "", invoice_number: row?.invoice_number ?? "", warranty_period_months: row?.warranty_period_months ?? 12, firmware_version: row?.firmware_version ?? "", ip_address: row?.ip_address ?? "", mac_address: row?.mac_address ?? "", location_notes: row?.location_notes ?? "", notes: row?.notes ?? "" });
  const set = (key: keyof CreateAssetPayload, value: string | number | null) => setForm((x) => ({ ...x, [key]: value }));
  const save = useMutation({ mutationFn: () => { const payload = { ...form, ip_address: form.ip_address || null }; return row ? updateAsset(row.id, payload) : createAsset(payload); }, onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>{t(row ? "action.editAsset" : "action.addAsset")}</DialogTitle><DialogDescription>{row?.asset_code || t("dialog.asset")}</DialogDescription></DialogHeader><div className="grid max-h-[65dvh] gap-3 overflow-auto sm:grid-cols-2">
    <SelectField value={form.category} onChange={(v) => set("category", v)}><option value="">{t("field.category")}</option>{CATEGORIES.map((x) => <option key={x} value={x}>{t(`category.${x}`)}</option>)}</SelectField>
    {form.category === "OTHER" && <SelectField value={form.custom_category ?? ""} onChange={(v) => set("custom_category", v || null)}><option value="">{t("field.customCategory")}</option>{(categories.data?.results ?? []).filter((x) => x.is_active && !x.is_system).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectField>}
    <Input placeholder={t("field.name")} value={form.name} onChange={(e) => set("name", e.target.value)} /><Input placeholder={t("field.serial")} value={form.serial_number} onChange={(e) => set("serial_number", e.target.value)} /><Input placeholder={t("field.brand")} value={form.brand} onChange={(e) => set("brand", e.target.value)} /><Input placeholder={t("field.model")} value={form.model} onChange={(e) => set("model", e.target.value)} /><Input type="date" value={form.purchase_date} onChange={(e) => set("purchase_date", e.target.value)} /><Input type="number" min="0" step="0.01" placeholder={t("field.purchasePrice")} value={form.purchase_price} onChange={(e) => set("purchase_price", e.target.value)} /><Input placeholder={t("field.supplier")} value={form.supplier} onChange={(e) => set("supplier", e.target.value)} /><Input placeholder={t("field.invoice")} value={form.invoice_number} onChange={(e) => set("invoice_number", e.target.value)} /><Input type="number" min="0" placeholder={t("field.warrantyMonths")} value={form.warranty_period_months} onChange={(e) => set("warranty_period_months", Number(e.target.value))} /><Input placeholder={t("field.firmware")} value={form.firmware_version} onChange={(e) => set("firmware_version", e.target.value)} /><Input placeholder={t("field.ipAddress")} value={form.ip_address ?? ""} onChange={(e) => set("ip_address", e.target.value || null)} /><Input placeholder={t("field.macAddress")} value={form.mac_address} onChange={(e) => set("mac_address", e.target.value)} /><Textarea placeholder={t("field.location")} value={form.location_notes} onChange={(e) => set("location_notes", e.target.value)} /><Textarea placeholder={t("field.notes")} value={form.notes} onChange={(e) => set("notes", e.target.value)} />
  </div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.category || !form.name || !form.serial_number || !form.purchase_date || !form.purchase_price || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function CategoryPanel() {
  const t = useTranslations("adminAssetManagement"); const qc = useQueryClient(); const { can } = useAuth(); const rows = useQuery({ queryKey: ["asset-categories"], queryFn: () => getAssetCategories({ page_size: 200 }) }); const [editing, setEditing] = useState<AssetCategoryDefinition | null | undefined>(undefined);
  const remove = useMutation({ mutationFn: deleteAssetCategory, onSuccess: () => qc.invalidateQueries({ queryKey: ["asset-categories"] }) });
  return <Panel loading={rows.isLoading} error={rows.isError}>{can("asset.manage") && <div className="flex justify-end border-b p-3"><Button onClick={() => setEditing(null)}><Plus />{t("action.addCategory")}</Button></div>}<Table><TableHeader><TableRow>{["code", "name", "description", "source", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.code}</TableCell><TableCell>{row.name}</TableCell><TableCell>{row.description || "-"}</TableCell><TableCell>{t(row.is_system ? "status.system" : "status.custom")}</TableCell><TableCell><StatusBadge label={t(row.is_active ? "status.active" : "status.inactive")} tone={row.is_active ? "positive" : "neutral"} /></TableCell><TableCell>{can("asset.manage") && <div className="flex gap-1"><Button size="icon-sm" variant="ghost" onClick={() => setEditing(row)}><Pencil /></Button>{!row.is_system && <Button size="icon-sm" variant="ghost" onClick={() => remove.mutate(row.id)}><Trash2 /></Button>}</div>}</TableCell></TableRow>)}</TableBody></Table>{editing !== undefined && <CategoryDialog row={editing} onClose={() => setEditing(undefined)} onSaved={() => qc.invalidateQueries({ queryKey: ["asset-categories"] })} />}</Panel>;
}

function CategoryDialog({ row, onClose, onSaved }: { row: AssetCategoryDefinition | null; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const [code, setCode] = useState(row?.code ?? ""); const [name, setName] = useState(row?.name ?? ""); const [description, setDescription] = useState(row?.description ?? ""); const [active, setActive] = useState(row?.is_active ?? true);
  const save = useMutation({ mutationFn: () => row ? updateAssetCategory(row.id, { name, description, is_active: active }) : createAssetCategory({ code, name, description }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t(row ? "action.editCategory" : "action.addCategory")}</DialogTitle><DialogDescription>{t("dialog.category")}</DialogDescription></DialogHeader><Input disabled={Boolean(row)} placeholder={t("field.code")} value={code} onChange={(e) => setCode(e.target.value)} /><Input placeholder={t("field.name")} value={name} onChange={(e) => setName(e.target.value)} /><Textarea placeholder={t("field.description")} value={description} onChange={(e) => setDescription(e.target.value)} />{row && <label className="flex items-center gap-2"><Switch checked={active} onCheckedChange={setActive} />{t("status.active")}</label>}<DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!code || !name || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function PurchasePanel() {
  const t = useTranslations("adminAssetManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const rows = useQuery({ queryKey: ["asset-purchases"], queryFn: () => getAssetPurchases({ page_size: 200 }) }); const [creating, setCreating] = useState(false); const [receiving, setReceiving] = useState<AssetPurchase | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}>{can("asset.manage") && <div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.addPurchase")}</Button></div>}<Table><TableHeader><TableRow>{["purchaseCode", "supplier", "date", "asset", "quantity", "received", "unitPrice", "total", "purchaser", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.purchase_code}</TableCell><TableCell>{row.supplier}</TableCell><TableCell>{df.date(row.purchase_date)}</TableCell><TableCell>{row.asset_name}<p className="text-xs text-muted-foreground">{t(`category.${row.category}`)}</p></TableCell><TableCell>{row.quantity}</TableCell><TableCell>{row.received_quantity}</TableCell><TableCell>RM {row.unit_price}</TableCell><TableCell>RM {row.total_amount}</TableCell><TableCell>{row.purchaser_name || "-"}</TableCell><TableCell><StatusBadge label={t(`purchaseStatus.${row.delivery_status}`)} tone={statusTone(row.delivery_status)} /></TableCell><TableCell>{can("asset.manage") && !["RECEIVED", "CANCELLED"].includes(row.delivery_status) && <Button size="sm" onClick={() => setReceiving(row)}><Download />{t("action.receive")}</Button>}</TableCell></TableRow>)}</TableBody></Table>{creating && <PurchaseDialog onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["asset-purchases"] })} />}{receiving && <ReceiveDialog row={receiving} onClose={() => setReceiving(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-purchases"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}</Panel>;
}

function PurchaseDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const categories = useQuery({ queryKey: ["asset-categories", "options"], queryFn: () => getAssetCategories({ page_size: 200 }) }); const [form, setForm] = useState({ supplier: "", purchase_date: "", category: "GATEWAY", custom_category: "", asset_name: "", brand: "", model: "", quantity: "1", unit_price: "", invoice_number: "", warranty_period_months: "12", notes: "" }); const set = (k: keyof typeof form, v: string) => setForm((x) => ({ ...x, [k]: v }));
  const save = useMutation({ mutationFn: () => createAssetPurchase({ ...form, custom_category: form.custom_category || null, quantity: Number(form.quantity), warranty_period_months: Number(form.warranty_period_months) }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{t("action.addPurchase")}</DialogTitle><DialogDescription>{t("dialog.purchase")}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Input placeholder={t("field.supplier")} value={form.supplier} onChange={(e) => set("supplier", e.target.value)} /><Input type="date" value={form.purchase_date} onChange={(e) => set("purchase_date", e.target.value)} /><SelectField value={form.category} onChange={(v) => set("category", v)}>{CATEGORIES.map((x) => <option key={x} value={x}>{t(`category.${x}`)}</option>)}</SelectField>{form.category === "OTHER" && <SelectField value={form.custom_category} onChange={(v) => set("custom_category", v)}><option value="">{t("field.customCategory")}</option>{(categories.data?.results ?? []).filter((x) => !x.is_system && x.is_active).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectField>}<Input placeholder={t("field.assetName")} value={form.asset_name} onChange={(e) => set("asset_name", e.target.value)} /><Input placeholder={t("field.brand")} value={form.brand} onChange={(e) => set("brand", e.target.value)} /><Input placeholder={t("field.model")} value={form.model} onChange={(e) => set("model", e.target.value)} /><Input type="number" min="1" placeholder={t("field.quantity")} value={form.quantity} onChange={(e) => set("quantity", e.target.value)} /><Input type="number" min="0" step="0.01" placeholder={t("field.unitPrice")} value={form.unit_price} onChange={(e) => set("unit_price", e.target.value)} /><Input placeholder={t("field.invoice")} value={form.invoice_number} onChange={(e) => set("invoice_number", e.target.value)} /><Input type="number" min="0" placeholder={t("field.warrantyMonths")} value={form.warranty_period_months} onChange={(e) => set("warranty_period_months", e.target.value)} /><Textarea className="sm:col-span-2" placeholder={t("field.notes")} value={form.notes} onChange={(e) => set("notes", e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.supplier || !form.purchase_date || !form.asset_name || !form.quantity || !form.unit_price || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function ReceiveDialog({ row, onClose, onSaved }: { row: AssetPurchase; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const [quantity, setQuantity] = useState(String(row.quantity - row.received_quantity)); const [receivedOn, setReceivedOn] = useState(new Date().toISOString().slice(0, 10)); const save = useMutation({ mutationFn: () => receiveAssetPurchase(row.id, { received_quantity: Number(quantity), received_on: receivedOn }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.receive")}</DialogTitle><DialogDescription>{row.purchase_code} / {row.asset_name}</DialogDescription></DialogHeader><Input type="number" min="1" max={row.quantity - row.received_quantity} value={quantity} onChange={(e) => setQuantity(e.target.value)} /><Input type="date" value={receivedOn} onChange={(e) => setReceivedOn(e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!quantity || !receivedOn || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

function InventoryPanel() {
  const t = useTranslations("adminAssetManagement"); const rows = useQuery({ queryKey: ["asset-stock"], queryFn: getAssetStock });
  return <Panel loading={rows.isLoading} error={rows.isError}><Table><TableHeader><TableRow>{["category", "total", "available", "installed", "borrowed", "maintenance", "faulty", "retired", "value"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data ?? []).map((row) => <TableRow key={row.category}><TableCell><TypeBadge label={t(`category.${row.category}`)} /></TableCell><TableCell>{row.total_quantity}</TableCell><TableCell>{row.in_stock_quantity}</TableCell><TableCell>{row.deployed_quantity}</TableCell><TableCell>{row.borrowed_quantity}</TableCell><TableCell>{row.maintenance_quantity}</TableCell><TableCell>{row.faulty_quantity}</TableCell><TableCell>{row.retired_quantity}</TableCell><TableCell>RM {row.total_value}</TableCell></TableRow>)}</TableBody></Table></Panel>;
}

function AssignmentPanel() {
  const t = useTranslations("adminAssetManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const rows = useQuery({ queryKey: ["asset-assignments"], queryFn: () => getAssetAssignments({ page_size: 200 }) }); const [creating, setCreating] = useState(false); const [returning, setReturning] = useState<AssetAssignment | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}>{can("asset.issue") && <div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.issueAsset")}</Button></div>}<Table><TableHeader><TableRow>{["assignmentCode", "asset", "holder", "borrowedOn", "expectedReturn", "actualReturn", "purpose", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.assignment_code}</TableCell><TableCell>{row.asset.asset_code}<p className="text-xs text-muted-foreground">{row.asset.name}</p></TableCell><TableCell>{row.holder_name}</TableCell><TableCell>{df.date(row.borrowed_on)}</TableCell><TableCell>{df.date(row.expected_return_on) || "-"}</TableCell><TableCell>{df.date(row.returned_on) || "-"}</TableCell><TableCell>{row.purpose}</TableCell><TableCell><StatusBadge label={t(`assignmentStatus.${row.status}`)} tone={statusTone(row.status)} /></TableCell><TableCell>{can("asset.issue") && ["BORROWED", "OVERDUE"].includes(row.status) && <Button size="sm" onClick={() => setReturning(row)}><RotateCcw />{t("action.return")}</Button>}</TableCell></TableRow>)}</TableBody></Table>{creating && <AssignmentDialog onClose={() => setCreating(false)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-assignments"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}{returning && <ReturnDialog row={returning} onClose={() => setReturning(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-assignments"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}</Panel>;
}

function AssignmentDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const options = useQuery({ queryKey: ["asset-options"], queryFn: getAssetOptions }); const assets = useQuery({ queryKey: ["assets", "assignable"], queryFn: () => getAssets({ page_size: 200, status: "IN_STOCK" }) }); const [form, setForm] = useState({ asset_id: "", holder_id: "", borrowed_on: "", expected_return_on: "", purpose: "", notes: "" }); const set = (k: keyof typeof form, v: string) => setForm((x) => ({ ...x, [k]: v })); const save = useMutation({ mutationFn: () => createAssetAssignment({ ...form, expected_return_on: form.expected_return_on || null }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.issueAsset")}</DialogTitle><DialogDescription>{t("dialog.assignment")}</DialogDescription></DialogHeader><SelectField value={form.asset_id} onChange={(v) => set("asset_id", v)}><option value="">{t("field.selectAsset")}</option>{(assets.data?.results ?? []).map((x) => <option key={x.id} value={x.id}>{x.asset_code} / {x.name}</option>)}</SelectField><SelectField value={form.holder_id} onChange={(v) => set("holder_id", v)}><option value="">{t("field.selectHolder")}</option>{(options.data?.users ?? []).map((x) => <option key={x.id} value={x.id}>{x.full_name} / {x.email}</option>)}</SelectField><Input type="date" value={form.borrowed_on} onChange={(e) => set("borrowed_on", e.target.value)} /><Input type="date" value={form.expected_return_on} onChange={(e) => set("expected_return_on", e.target.value)} /><Textarea placeholder={t("field.purpose")} value={form.purpose} onChange={(e) => set("purpose", e.target.value)} /><Textarea placeholder={t("field.notes")} value={form.notes} onChange={(e) => set("notes", e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.asset_id || !form.holder_id || !form.borrowed_on || !form.purpose || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function ReturnDialog({ row, onClose, onSaved }: { row: AssetAssignment; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const [returnedOn, setReturnedOn] = useState(new Date().toISOString().slice(0, 10)); const [condition, setCondition] = useState(""); const save = useMutation({ mutationFn: () => returnAssetAssignment(row.id, { returned_on: returnedOn, return_condition: condition }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.return")}</DialogTitle><DialogDescription>{row.asset.asset_code} / {row.holder_name}</DialogDescription></DialogHeader><Input type="date" value={returnedOn} onChange={(e) => setReturnedOn(e.target.value)} /><Textarea placeholder={t("field.returnCondition")} value={condition} onChange={(e) => setCondition(e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!returnedOn || !condition || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

function InstallationPanel() {
  const t = useTranslations("adminAssetManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const rows = useQuery({ queryKey: ["asset-installations"], queryFn: () => getAssetInstallations({ page_size: 200 }) }); const [creating, setCreating] = useState(false); const [transitioning, setTransitioning] = useState<AssetInstallation | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}>{can("asset.manage") && <div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.installAsset")}</Button></div>}<Table><TableHeader><TableRow>{["installationCode", "asset", "company", "project", "location", "installedOn", "installer", "activatedOn", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.installation_code}</TableCell><TableCell>{row.asset.asset_code}<p className="text-xs text-muted-foreground">{row.asset.name}</p></TableCell><TableCell>{row.company_name}</TableCell><TableCell>{row.project_name || "-"}</TableCell><TableCell>{row.location}</TableCell><TableCell>{df.date(row.installed_on)}</TableCell><TableCell>{row.installed_by_name || "-"}</TableCell><TableCell>{df.date(row.activated_on) || "-"}</TableCell><TableCell><StatusBadge label={t(`installationStatus.${row.status}`)} tone={statusTone(row.status)} /></TableCell><TableCell>{can("asset.manage") && row.status !== "REMOVED" && <Button size="sm" onClick={() => setTransitioning(row)}>{t("action.changeStatus")}</Button>}</TableCell></TableRow>)}</TableBody></Table>{creating && <InstallationDialog onClose={() => setCreating(false)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-installations"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}{transitioning && <InstallationStatusDialog row={transitioning} onClose={() => setTransitioning(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-installations"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}</Panel>;
}

function InstallationDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const options = useQuery({ queryKey: ["asset-options"], queryFn: getAssetOptions }); const assets = useQuery({ queryKey: ["assets", "installable"], queryFn: () => getAssets({ page_size: 200, is_active: true }) }); const [form, setForm] = useState({ asset_id: "", company_id: "", project: "", location: "", installed_on: "", installed_by_id: "", notes: "" }); const set = (k: keyof typeof form, v: string) => setForm((x) => ({ ...x, [k]: v, ...(k === "company_id" ? { project: "" } : {}) })); const save = useMutation({ mutationFn: () => createAssetInstallation({ ...form, project: form.project || null, installed_by_id: form.installed_by_id || null }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.installAsset")}</DialogTitle><DialogDescription>{t("dialog.installation")}</DialogDescription></DialogHeader><SelectField value={form.asset_id} onChange={(v) => set("asset_id", v)}><option value="">{t("field.selectAsset")}</option>{(assets.data?.results ?? []).filter((x) => !["BORROWED", "MAINTENANCE", "FAULTY", "RETIRED"].includes(x.status)).map((x) => <option key={x.id} value={x.id}>{x.asset_code} / {x.name}</option>)}</SelectField><SelectField value={form.company_id} onChange={(v) => set("company_id", v)}><option value="">{t("field.selectCompany")}</option>{(options.data?.companies ?? []).map((x) => <option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</SelectField><SelectField value={form.project} onChange={(v) => set("project", v)}><option value="">{t("field.noProject")}</option>{(options.data?.projects ?? []).filter((x) => x.company_id === form.company_id).map((x) => <option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</SelectField><SelectField value={form.installed_by_id} onChange={(v) => set("installed_by_id", v)}><option value="">{t("field.currentOperator")}</option>{(options.data?.users ?? []).map((x) => <option key={x.id} value={x.id}>{x.full_name}</option>)}</SelectField><Input placeholder={t("field.location")} value={form.location} onChange={(e) => set("location", e.target.value)} /><Input type="date" value={form.installed_on} onChange={(e) => set("installed_on", e.target.value)} /><Textarea placeholder={t("field.notes")} value={form.notes} onChange={(e) => set("notes", e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.asset_id || !form.company_id || !form.location || !form.installed_on || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function InstallationStatusDialog({ row, onClose, onSaved }: { row: AssetInstallation; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const choices: InstallationStatus[] = row.status === "INSTALLED" ? ["ACTIVE", "REMOVED"] : row.status === "ACTIVE" ? ["INACTIVE", "REMOVED"] : ["ACTIVE", "REMOVED"]; const [status, setStatus] = useState<InstallationStatus>(choices[0]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const save = useMutation({ mutationFn: () => transitionAssetInstallation(row.id, { status, ...(status === "ACTIVE" ? { activated_on: date } : status === "REMOVED" ? { removed_on: date } : {}) }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.changeStatus")}</DialogTitle><DialogDescription>{row.installation_code}</DialogDescription></DialogHeader><SelectField value={status} onChange={(v) => setStatus(v as InstallationStatus)}>{choices.map((x) => <option key={x} value={x}>{t(`installationStatus.${x}`)}</option>)}</SelectField>{status !== "INACTIVE" && <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} />}<DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

function TransferPanel() {
  const t = useTranslations("adminAssetManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const rows = useQuery({ queryKey: ["asset-movements", "transfers"], queryFn: () => getMovements({ page_size: 200, type: "TRANSFER" }) }); const [creating, setCreating] = useState(false);
  return <Panel loading={rows.isLoading} error={rows.isError}>{can("asset.transfer") && <div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.transferAsset")}</Button></div>}<Table><TableHeader><TableRow>{["movementCode", "asset", "from", "to", "date", "reason", "operator"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.movement_code}</TableCell><TableCell>{row.asset.asset_code}<p className="text-xs text-muted-foreground">{row.asset.name}</p></TableCell><TableCell>{row.from_user_name || row.from_department_name || row.from_project_name || row.from_warehouse || row.from_location || "-"}</TableCell><TableCell>{row.to_user_name || row.to_department_name || row.to_project_name || row.to_warehouse || row.to_location || "-"}</TableCell><TableCell>{df.date(row.movement_date)}</TableCell><TableCell>{row.reason}</TableCell><TableCell>{row.handled_by_name || "-"}</TableCell></TableRow>)}</TableBody></Table>{creating && <TransferDialog onClose={() => setCreating(false)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-movements"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}</Panel>;
}

function TransferDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const options = useQuery({ queryKey: ["asset-options"], queryFn: getAssetOptions }); const assets = useQuery({ queryKey: ["assets", "transferable"], queryFn: () => getAssets({ page_size: 200, is_active: true }) }); const [destination, setDestination] = useState("warehouse"); const [target, setTarget] = useState(""); const [movementDate, setMovementDate] = useState(""); const [reason, setReason] = useState(""); const [notes, setNotes] = useState(""); const [assetId, setAssetId] = useState("");
  const save = useMutation({ mutationFn: () => createMovement({ asset_id: assetId, type: "TRANSFER", movement_date: movementDate, reason, notes, ...(destination === "user" ? { to_user: target } : destination === "department" ? { to_department: target } : destination === "project" ? { to_project: target } : destination === "company" ? { to_company: target } : { to_warehouse: target }) }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.transferAsset")}</DialogTitle><DialogDescription>{t("dialog.transfer")}</DialogDescription></DialogHeader><SelectField value={assetId} onChange={setAssetId}><option value="">{t("field.selectAsset")}</option>{(assets.data?.results ?? []).filter((x) => x.status !== "RETIRED").map((x) => <option key={x.id} value={x.id}>{x.asset_code} / {x.name}</option>)}</SelectField><SelectField value={destination} onChange={(v) => { setDestination(v); setTarget(""); }}>{["user", "department", "warehouse", "project", "company"].map((x) => <option key={x} value={x}>{t(`destination.${x}`)}</option>)}</SelectField>{destination === "warehouse" ? <Input placeholder={t("field.warehouse")} value={target} onChange={(e) => setTarget(e.target.value)} /> : <SelectField value={target} onChange={setTarget}><option value="">{t("field.selectDestination")}</option>{(destination === "user" ? options.data?.users : destination === "department" ? options.data?.departments : destination === "project" ? options.data?.projects : options.data?.companies)?.map((x) => <option key={x.id} value={x.id}>{"code" in x ? `${x.code} / ` : ""}{"full_name" in x ? x.full_name : x.name}</option>)}</SelectField>}<Input type="date" value={movementDate} onChange={(e) => setMovementDate(e.target.value)} /><Textarea placeholder={t("field.reason")} value={reason} onChange={(e) => setReason(e.target.value)} /><Textarea placeholder={t("field.notes")} value={notes} onChange={(e) => setNotes(e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!assetId || !target || !movementDate || !reason || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function MaintenancePanel({ repairs }: { repairs: boolean }) {
  const t = useTranslations("adminAssetManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const rows = useQuery({ queryKey: ["asset-maintenance", repairs], queryFn: () => getAssetMaintenance({ page_size: 200, ...(repairs ? { type: "CORRECTIVE" } : {}) }) }); const filtered = (rows.data?.results ?? []).filter((x) => repairs ? x.type === "CORRECTIVE" : x.type !== "CORRECTIVE"); const [creating, setCreating] = useState(false); const [completing, setCompleting] = useState<AssetMaintenance | null>(null); const start = useMutation({ mutationFn: startAssetMaintenance, onSuccess: () => { qc.invalidateQueries({ queryKey: ["asset-maintenance"] }); qc.invalidateQueries({ queryKey: ["assets"] }); } });
  return <Panel loading={rows.isLoading} error={rows.isError}>{can("asset.maintain") && <div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t(repairs ? "action.addRepair" : "action.addMaintenance")}</Button></div>}<Table><TableHeader><TableRow>{["maintenanceCode", "asset", "type", "faultDate", "scheduledDate", "nextDate", "technician", "description", "result", "cost", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map((row) => <TableRow key={row.id}><TableCell>{row.maintenance_code}</TableCell><TableCell>{row.asset.asset_code}<p className="text-xs text-muted-foreground">{row.asset.name}</p></TableCell><TableCell>{t(`maintenanceType.${row.type}`)}</TableCell><TableCell>{df.date(row.fault_date) || "-"}</TableCell><TableCell>{df.date(row.scheduled_date)}</TableCell><TableCell>{df.date(row.next_maintenance_date) || "-"}</TableCell><TableCell>{row.technician_name || "-"}</TableCell><TableCell>{row.description}</TableCell><TableCell>{row.result || "-"}</TableCell><TableCell>{row.total_cost ? `RM ${row.total_cost}` : "-"}</TableCell><TableCell><StatusBadge label={t(`maintenanceStatus.${row.status}`)} tone={statusTone(row.status)} /></TableCell><TableCell>{can("asset.maintain") && ["SCHEDULED", "IN_PROGRESS"].includes(row.status) && <div className="flex gap-1">{row.status === "SCHEDULED" && <Button size="sm" variant="outline" onClick={() => start.mutate(row.id)}><Wrench />{t("action.start")}</Button>}<Button size="sm" onClick={() => setCompleting(row)}><Check />{t("action.complete")}</Button></div>}</TableCell></TableRow>)}</TableBody></Table>{creating && <MaintenanceDialog repairs={repairs} onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["asset-maintenance"] })} />}{completing && <MaintenanceCompleteDialog row={completing} onClose={() => setCompleting(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-maintenance"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}</Panel>;
}

function MaintenanceDialog({ repairs, onClose, onSaved }: { repairs: boolean; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const options = useQuery({ queryKey: ["asset-options"], queryFn: getAssetOptions }); const assets = useQuery({ queryKey: ["assets", "maintenance-options"], queryFn: () => getAssets({ page_size: 200, is_active: true }) }); const [form, setForm] = useState({ asset_id: "", type: repairs ? "CORRECTIVE" : "PREVENTIVE", fault_date: "", scheduled_date: "", description: "", technician_id: "", is_recurring: false }); const set = (k: keyof typeof form, v: string | boolean) => setForm((x) => ({ ...x, [k]: v })); const save = useMutation({ mutationFn: () => createAssetMaintenance({ ...form, fault_date: form.fault_date || null, technician_id: form.technician_id || null }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t(repairs ? "action.addRepair" : "action.addMaintenance")}</DialogTitle><DialogDescription>{t("dialog.maintenance")}</DialogDescription></DialogHeader><SelectField value={form.asset_id} onChange={(v) => set("asset_id", v)}><option value="">{t("field.selectAsset")}</option>{(assets.data?.results ?? []).filter((x) => x.status !== "RETIRED").map((x) => <option key={x.id} value={x.id}>{x.asset_code} / {x.name}</option>)}</SelectField>{!repairs && <SelectField value={form.type} onChange={(v) => set("type", v)}>{MAINTENANCE_TYPES.filter((x) => x !== "CORRECTIVE").map((x) => <option key={x} value={x}>{t(`maintenanceType.${x}`)}</option>)}</SelectField>}{repairs && <Input type="date" value={form.fault_date} onChange={(e) => set("fault_date", e.target.value)} />}<Input type="date" value={form.scheduled_date} onChange={(e) => set("scheduled_date", e.target.value)} /><SelectField value={form.technician_id} onChange={(v) => set("technician_id", v)}><option value="">{t("field.noTechnician")}</option>{(options.data?.users ?? []).map((x) => <option key={x.id} value={x.id}>{x.full_name}</option>)}</SelectField><Textarea placeholder={t("field.description")} value={form.description} onChange={(e) => set("description", e.target.value)} />{!repairs && <label className="flex items-center gap-2"><Switch checked={form.is_recurring} onCheckedChange={(v) => set("is_recurring", v)} />{t("field.recurring")}</label>}<DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.asset_id || !form.scheduled_date || !form.description || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function MaintenanceCompleteDialog({ row, onClose, onSaved }: { row: AssetMaintenance; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const [form, setForm] = useState({ completed_date: new Date().toISOString().slice(0, 10), work_performed: "", parts_replaced: "", labor_cost: "0.00", parts_cost: "0.00", result: "", next_maintenance_date: "" }); const set = (k: keyof typeof form, v: string) => setForm((x) => ({ ...x, [k]: v })); const save = useMutation({ mutationFn: () => completeAssetMaintenance(row.id, { ...form, next_maintenance_date: form.next_maintenance_date || null }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{t("action.complete")}</DialogTitle><DialogDescription>{row.maintenance_code}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={form.completed_date} onChange={(e) => set("completed_date", e.target.value)} /><Input type="date" value={form.next_maintenance_date} onChange={(e) => set("next_maintenance_date", e.target.value)} /><Textarea placeholder={t("field.workPerformed")} value={form.work_performed} onChange={(e) => set("work_performed", e.target.value)} /><Textarea placeholder={t("field.partsReplaced")} value={form.parts_replaced} onChange={(e) => set("parts_replaced", e.target.value)} /><Input type="number" min="0" step="0.01" placeholder={t("field.laborCost")} value={form.labor_cost} onChange={(e) => set("labor_cost", e.target.value)} /><Input type="number" min="0" step="0.01" placeholder={t("field.partsCost")} value={form.parts_cost} onChange={(e) => set("parts_cost", e.target.value)} /><Textarea className="sm:col-span-2" placeholder={t("field.result")} value={form.result} onChange={(e) => set("result", e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.completed_date || !form.work_performed || !form.result || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

function DisposalPanel() {
  const t = useTranslations("adminAssetManagement"); const df = useDateFormat(); const qc = useQueryClient(); const { can } = useAuth(); const rows = useQuery({ queryKey: ["asset-disposals"], queryFn: () => getAssetDisposals({ page_size: 200 }) }); const [creating, setCreating] = useState(false); const [acting, setActing] = useState<AssetDisposal | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}>{can("asset.dispose") && <div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.requestDisposal")}</Button></div>}<Table><TableHeader><TableRow>{["disposalCode", "asset", "requestedOn", "requester", "method", "reason", "approver", "disposalDate", "status", "actions"].map((x) => <TableHead key={x}>{t(`column.${x}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.disposal_code}</TableCell><TableCell>{row.asset.asset_code}<p className="text-xs text-muted-foreground">{row.asset.name}</p></TableCell><TableCell>{df.date(row.requested_on)}</TableCell><TableCell>{row.requested_by_name || "-"}</TableCell><TableCell>{row.disposal_method}</TableCell><TableCell>{row.reason}</TableCell><TableCell>{row.approved_by_name || "-"}</TableCell><TableCell>{df.date(row.disposal_date) || "-"}</TableCell><TableCell><StatusBadge label={t(`disposalStatus.${row.status}`)} tone={statusTone(row.status)} /></TableCell><TableCell>{can("asset.dispose") && ["REQUESTED", "APPROVED"].includes(row.status) && <Button size="sm" onClick={() => setActing(row)}>{t("action.process")}</Button>}</TableCell></TableRow>)}</TableBody></Table>{creating && <DisposalDialog onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["asset-disposals"] })} />}{acting && <DisposalDecisionDialog row={acting} onClose={() => setActing(null)} onSaved={() => { qc.invalidateQueries({ queryKey: ["asset-disposals"] }); qc.invalidateQueries({ queryKey: ["assets"] }); }} />}</Panel>;
}

function DisposalDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const assets = useQuery({ queryKey: ["assets", "disposal-options"], queryFn: () => getAssets({ page_size: 200, is_active: true }) }); const [form, setForm] = useState({ asset_id: "", reason: "", disposal_method: "", salvage_value: "", disposal_cost: "", notes: "" }); const set = (k: keyof typeof form, v: string) => setForm((x) => ({ ...x, [k]: v })); const save = useMutation({ mutationFn: () => createAssetDisposal({ ...form, salvage_value: form.salvage_value || null, disposal_cost: form.disposal_cost || null }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.requestDisposal")}</DialogTitle><DialogDescription>{t("dialog.disposal")}</DialogDescription></DialogHeader><SelectField value={form.asset_id} onChange={(v) => set("asset_id", v)}><option value="">{t("field.selectAsset")}</option>{(assets.data?.results ?? []).filter((x) => x.status !== "RETIRED").map((x) => <option key={x.id} value={x.id}>{x.asset_code} / {x.name}</option>)}</SelectField><Input placeholder={t("field.disposalMethod")} value={form.disposal_method} onChange={(e) => set("disposal_method", e.target.value)} /><Textarea placeholder={t("field.reason")} value={form.reason} onChange={(e) => set("reason", e.target.value)} /><div className="grid grid-cols-2 gap-3"><Input type="number" min="0" step="0.01" placeholder={t("field.salvageValue")} value={form.salvage_value} onChange={(e) => set("salvage_value", e.target.value)} /><Input type="number" min="0" step="0.01" placeholder={t("field.disposalCost")} value={form.disposal_cost} onChange={(e) => set("disposal_cost", e.target.value)} /></div><Textarea placeholder={t("field.notes")} value={form.notes} onChange={(e) => set("notes", e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.asset_id || !form.reason || !form.disposal_method || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function DisposalDecisionDialog({ row, onClose, onSaved }: { row: AssetDisposal; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminAssetManagement"); const [decision, setDecision] = useState(row.status === "APPROVED" ? "COMPLETE" : "APPROVE"); const [note, setNote] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const choices = row.status === "APPROVED" ? ["COMPLETE"] : ["APPROVE", "REJECT"]; const save = useMutation({ mutationFn: () => decideAssetDisposal(row.id, { decision, note, ...(decision === "COMPLETE" ? { disposal_date: date } : {}) }), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.process")}</DialogTitle><DialogDescription>{row.disposal_code}</DialogDescription></DialogHeader><SelectField value={decision} onChange={setDecision}>{choices.map((x) => <option key={x} value={x}>{t(`decision.${x}`)}</option>)}</SelectField>{decision === "COMPLETE" && <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} />}<Textarea placeholder={t("field.note")} value={note} onChange={(e) => setNote(e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={(decision === "REJECT" && !note.trim()) || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

const REPORTS: Record<string, string[]> = {
  assets: ["asset_code", "name", "category", "brand", "model", "serial_number", "purchase_date", "warranty_expires_on", "status", "holder_name", "deployed_company_name", "project_name"],
  inventory: ["category", "total", "available", "installed", "borrowed", "maintenance", "retired", "value"],
  purchases: ["purchase_code", "supplier", "purchase_date", "asset_name", "quantity", "received_quantity", "unit_price", "total_amount", "purchaser_name", "delivery_status"],
  assignments: ["assignment_code", "asset", "holder_name", "borrowed_on", "expected_return_on", "returned_on", "status", "purpose"],
  installations: ["installation_code", "asset", "company_name", "project_name", "location", "installed_on", "installed_by_name", "activated_on", "status"],
  movements: ["movement_code", "asset", "type", "from_location", "to_location", "movement_date", "reason", "handled_by_name"],
  repairs: ["maintenance_code", "asset", "fault_date", "scheduled_date", "completed_date", "technician_name", "description", "result", "total_cost", "status"],
  maintenance: ["maintenance_code", "asset", "type", "scheduled_date", "completed_date", "next_maintenance_date", "technician_name", "description", "result", "total_cost", "status"],
  disposals: ["disposal_code", "asset", "requested_on", "requested_by_name", "disposal_date", "reason", "disposal_method", "approved_by_name", "status"],
};

function ReportPanel() {
  const t = useTranslations("adminAssetManagement"); const summary = useQuery({ queryKey: ["asset-report-summary"], queryFn: getAssetReportSummary }); const [busy, setBusy] = useState("");
  async function run(dataset: string, format: "xlsx" | "pdf") { setBusy(`${dataset}-${format}`); try { await exportAssetReport(dataset, format, REPORTS[dataset].map((key) => ({ key, label: t(`exportColumn.${key}`) })), t(`report.${dataset}`)); } finally { setBusy(""); } }
  return <Panel loading={summary.isLoading} error={summary.isError}><div className="grid md:grid-cols-2 xl:grid-cols-3">{Object.keys(REPORTS).map((dataset) => <div key={dataset} className="border-b border-r p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{t(`report.${dataset}`)}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{dataset === "inventory" ? summary.data?.inventory?.length ?? 0 : summary.data?.[dataset as keyof typeof summary.data] as number ?? 0}</p></div><div className="flex gap-1"><Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={() => void run(dataset, "xlsx")}>{busy === `${dataset}-xlsx` ? <Loader2 className="animate-spin" /> : <Download />}XLSX</Button><Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={() => void run(dataset, "pdf")}>{busy === `${dataset}-pdf` ? <Loader2 className="animate-spin" /> : <Download />}PDF</Button></div></div></div>)}</div></Panel>;
}
