"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Check, FileDown, Loader2, MessageSquareReply, Plus, Save } from "lucide-react";
import Link from "next/link";
import { useTranslations } from "next-intl";
import { useState } from "react";

import { AuditLogs } from "@/components/audit/audit-logs";
import { ListHeader, StatusBadge } from "@/components/shared/page-primitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import type { CompanyRow } from "@/interfaces/company";
import type { CustomerEnquiry, CustomerFeedback, CustomerTraining, EnquiryStatus, TrainingStatus } from "@/interfaces/crm";
import { useDateFormat } from "@/lib/dates";
import { getCompanies } from "@/services/companies.service";
import {
  createEnquiry, createFeedback, createServiceRecord, createTraining, createVisit,
  exportCustomerServiceReport, getCustomerServiceSummary, getEnquiries, getFeedback,
  getServiceRecords, getTraining, getVisits, respondFeedback, updateEnquiryStatus,
  updateTrainingStatus, type EnquiryPayload, type FeedbackPayload,
  type ServiceRecordPayload, type TrainingPayload, type VisitPayload,
} from "@/services/crm.service";

export type CustomerServiceSection = "overview" | "customers" | "enquiries" | "training" | "visits" | "feedback" | "service" | "reports" | "activity";
const SUBMODULES: Array<{ section: Exclude<CustomerServiceSection, "overview">; number: string }> = [
  { section: "customers", number: "14.2.1" }, { section: "enquiries", number: "14.2.2" },
  { section: "training", number: "14.2.3" }, { section: "visits", number: "14.2.4" },
  { section: "feedback", number: "14.2.5" }, { section: "service", number: "14.2.6" },
  { section: "reports", number: "14.2.7" }, { section: "activity", number: "14.2.8" },
];
const ENQUIRY_STATUSES: EnquiryStatus[] = ["NEW", "CONTACTED", "IN_PROGRESS", "QUOTED", "WON", "LOST", "CANCELLED"];

export function CustomerServiceWorkspace({ section = "overview" }: { section?: CustomerServiceSection }) {
  const t = useTranslations("adminCustomerService");
  if (section === "activity") return <AuditLogs fixedCategory="CUSTOMER_SERVICE" title={t("section.activity.title")} subtitle={t("section.activity.subtitle")} />;
  if (section === "overview") return <Overview />;
  return <div className="flex h-[calc(100dvh-5rem)] flex-col gap-4">
    <ListHeader title={t(`section.${section}.title`)} subtitle={t(`section.${section}.subtitle`)} />
    {section === "customers" && <CustomerPanel />}
    {section === "enquiries" && <EnquiryPanel />}
    {section === "training" && <TrainingPanel />}
    {section === "visits" && <VisitPanel />}
    {section === "feedback" && <FeedbackPanel />}
    {section === "service" && <ServicePanel />}
    {section === "reports" && <ReportPanel />}
  </div>;
}

function Overview() {
  const t = useTranslations("adminCustomerService");
  const summary = useQuery({ queryKey: ["customer-service-summary"], queryFn: getCustomerServiceSummary });
  return <div className="flex h-[calc(100dvh-5rem)] flex-col gap-4">
    <ListHeader title={t("title")} subtitle={t("subtitle")} />
    <div className="grid overflow-hidden rounded-lg border bg-card shadow-sm sm:grid-cols-2 xl:grid-cols-4">
      {[["customers", summary.data?.customers ?? 0], ["enquiries", summary.data?.enquiries ?? 0], ["service", summary.data?.service_records ?? 0], ["completion", `${summary.data?.completion_rate ?? 0}%`]].map(([key, value]) => <div key={key} className="border-b border-r px-5 py-4"><p className="text-xs text-muted-foreground">{t(`metric.${key}`)}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>)}
    </div>
    <div className="min-h-0 flex-1 overflow-y-auto rounded-lg border bg-card shadow-sm"><div className="grid md:grid-cols-2 xl:grid-cols-3">{SUBMODULES.map((item) => <Link key={item.section} href={`/customer-service/${item.section}`} className="flex min-h-20 items-center gap-3 border-b border-r px-5 py-4 hover:bg-muted/40"><span className="flex-1 font-medium">{t(`section.${item.section}.title`)}</span><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link>)}</div></div>
  </div>;
}

function Panel({ loading, error, children }: { loading: boolean; error: boolean; children: React.ReactNode }) {
  const t = useTranslations("adminCustomerService");
  if (loading) return <div className="flex min-h-48 flex-1 items-center justify-center rounded-lg border bg-card shadow-sm"><Loader2 className="mr-2 animate-spin" />{t("loading")}</div>;
  if (error) return <div className="rounded-lg border border-destructive/25 bg-destructive/5 p-5 text-destructive">{t("loadError")}</div>;
  return <div className="min-h-0 flex-1 overflow-auto rounded-lg border bg-card shadow-sm">{children}</div>;
}

function CompanySelect({ companies, value, onChange }: { companies: CompanyRow[]; value: string; onChange: (value: string) => void }) {
  const t = useTranslations("adminCustomerService");
  return <select className="h-8 rounded-md border bg-background px-2" value={value} onChange={(e) => onChange(e.target.value)}><option value="">{t("field.selectCompany")}</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.code} / {company.name}</option>)}</select>;
}

function CustomerPanel() {
  const t = useTranslations("adminCustomerService");
  const rows = useQuery({ queryKey: ["companies", "customer-service"], queryFn: () => getCompanies({ page_size: 200, sort_by: "name" }) });
  return <Panel loading={rows.isLoading} error={rows.isError}><Table><TableHeader><TableRow>{["code", "company", "type", "contact", "email", "state", "status"].map((key) => <TableHead key={key}>{t(`column.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.code}</TableCell><TableCell>{row.name}</TableCell><TableCell>{t(`companyType.${row.type}`)}</TableCell><TableCell>{row.contact_person || "-"}<p className="text-xs text-muted-foreground">{row.contact_phone || "-"}</p></TableCell><TableCell>{row.contact_email || "-"}</TableCell><TableCell>{row.state || "-"}</TableCell><TableCell><StatusBadge label={row.status} tone={row.status === "ACTIVE" ? "positive" : "warning"} /></TableCell></TableRow>)}</TableBody></Table></Panel>;
}

function EnquiryPanel() {
  const t = useTranslations("adminCustomerService"); const df = useDateFormat(); const qc = useQueryClient();
  const rows = useQuery({ queryKey: ["customer-enquiries"], queryFn: () => getEnquiries({ page_size: 200 }) });
  const [creating, setCreating] = useState(false); const [processing, setProcessing] = useState<CustomerEnquiry | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}><div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.addEnquiry")}</Button></div><Table><TableHeader><TableRow>{["code", "company", "contact", "subject", "handler", "date", "status", "actions"].map((key) => <TableHead key={key}>{t(`column.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.enquiry_code}</TableCell><TableCell>{row.company_name}</TableCell><TableCell>{row.contact_person}<p className="text-xs text-muted-foreground">{row.contact_phone}</p></TableCell><TableCell>{row.subject}</TableCell><TableCell>{row.assigned_to_name || "-"}</TableCell><TableCell>{df.date(row.created_at)}</TableCell><TableCell><StatusBadge label={t(`enquiryStatus.${row.status}`)} tone={row.status === "WON" ? "positive" : row.status === "LOST" || row.status === "CANCELLED" ? "danger" : "warning"} /></TableCell><TableCell><Button size="sm" variant="outline" onClick={() => setProcessing(row)}><MessageSquareReply />{t("action.process")}</Button></TableCell></TableRow>)}</TableBody></Table>{creating && <EnquiryDialog onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-enquiries"] })} />}{processing && <EnquiryStatusDialog row={processing} onClose={() => setProcessing(null)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-enquiries"] })} />}</Panel>;
}

function EnquiryDialog({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminCustomerService"); const [form, setForm] = useState<EnquiryPayload>({ source: "DIRECT", company_name: "", contact_person: "", contact_phone: "", contact_email: "", subject: "", message: "", requirements: "" });
  const set = (key: keyof EnquiryPayload, value: string) => setForm((x) => ({ ...x, [key]: value })); const save = useMutation({ mutationFn: () => createEnquiry(form), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{t("action.addEnquiry")}</DialogTitle><DialogDescription>{t("dialog.enquiry")}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><select className="h-8 rounded-md border bg-background px-2" value={form.source} onChange={(e) => set("source", e.target.value)}>{["WEBSITE", "REFERRAL", "PARTNER", "SOCIAL_MEDIA", "DIRECT", "EVENT", "OTHER"].map((x) => <option key={x} value={x}>{t(`source.${x}`)}</option>)}</select><Input placeholder={t("field.companyName")} value={form.company_name} onChange={(e) => set("company_name", e.target.value)} /><Input placeholder={t("field.contactPerson")} value={form.contact_person} onChange={(e) => set("contact_person", e.target.value)} /><Input placeholder={t("field.phone")} value={form.contact_phone} onChange={(e) => set("contact_phone", e.target.value)} /><Input type="email" placeholder={t("field.email")} value={form.contact_email} onChange={(e) => set("contact_email", e.target.value)} /><Input placeholder={t("field.subject")} value={form.subject} onChange={(e) => set("subject", e.target.value)} /><Textarea className="sm:col-span-2" placeholder={t("field.content")} value={form.message} onChange={(e) => set("message", e.target.value)} /><Textarea className="sm:col-span-2" placeholder={t("field.requirements")} value={form.requirements} onChange={(e) => set("requirements", e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.company_name || !form.contact_person || !form.contact_email || !form.subject || !form.message || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function EnquiryStatusDialog({ row, onClose, onSaved }: { row: CustomerEnquiry; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminCustomerService"); const [status, setStatus] = useState<EnquiryStatus>(row.status); const [result, setResult] = useState(""); const [lostReason, setLostReason] = useState(""); const save = useMutation({ mutationFn: () => updateEnquiryStatus(row.id, status, result, lostReason), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.process")}</DialogTitle><DialogDescription>{row.enquiry_code} / {row.company_name}</DialogDescription></DialogHeader><select className="h-8 rounded-md border bg-background px-2" value={status} onChange={(e) => setStatus(e.target.value as EnquiryStatus)}>{ENQUIRY_STATUSES.map((x) => <option key={x} value={x}>{t(`enquiryStatus.${x}`)}</option>)}</select>{status === "LOST" && <Textarea placeholder={t("field.lostReason")} value={lostReason} onChange={(e) => setLostReason(e.target.value)} />}<Textarea placeholder={t("field.result")} value={result} onChange={(e) => setResult(e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={(status === "LOST" && !lostReason.trim()) || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>;
}

function useCompanyOptions() { return useQuery({ queryKey: ["companies", "crm-options"], queryFn: () => getCompanies({ page_size: 200, sort_by: "name" }) }); }

function TrainingPanel() {
  const t = useTranslations("adminCustomerService"); const df = useDateFormat(); const qc = useQueryClient(); const companies = useCompanyOptions();
  const rows = useQuery({ queryKey: ["customer-training"], queryFn: () => getTraining({ page_size: 200 }) }); const [creating, setCreating] = useState(false); const [processing, setProcessing] = useState<CustomerTraining | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}><div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.addTraining")}</Button></div><Table><TableHeader><TableRow>{["code", "company", "type", "subject", "date", "trainer", "attendees", "status", "actions"].map((key) => <TableHead key={key}>{t(`column.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.training_code}</TableCell><TableCell>{row.company_name}</TableCell><TableCell>{t(`trainingType.${row.type}`)}</TableCell><TableCell>{row.title}</TableCell><TableCell>{df.date(row.scheduled_date)}</TableCell><TableCell>{row.trainer_name || "-"}</TableCell><TableCell>{row.attendee_count}</TableCell><TableCell><StatusBadge label={t(`trainingStatus.${row.status}`)} tone={row.status === "COMPLETED" ? "positive" : row.status === "CANCELLED" ? "danger" : "warning"} /></TableCell><TableCell><Button size="sm" variant="outline" onClick={() => setProcessing(row)}>{t("action.updateStatus")}</Button></TableCell></TableRow>)}</TableBody></Table>{creating && <TrainingDialog companies={companies.data?.results ?? []} onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-training"] })} />}{processing && <TrainingStatusDialog row={processing} onClose={() => setProcessing(null)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-training"] })} />}</Panel>;
}

function TrainingDialog({ companies, onClose, onSaved }: { companies: CompanyRow[]; onClose: () => void; onSaved: () => void }) {
  const t = useTranslations("adminCustomerService"); const [form, setForm] = useState<TrainingPayload>({ company: "", type: "ONBOARDING", title: "", description: "", scheduled_date: "", scheduled_time: "09:00", duration_hours: "1", location: "", attendee_count: 0 }); const set = (key: keyof TrainingPayload, value: unknown) => setForm((x) => ({ ...x, [key]: value })); const save = useMutation({ mutationFn: () => createTraining(form), onSuccess: () => { onSaved(); onClose(); } });
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{t("action.addTraining")}</DialogTitle><DialogDescription>{t("dialog.training")}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><CompanySelect companies={companies} value={form.company} onChange={(x) => set("company", x)} /><select className="h-8 rounded-md border bg-background px-2" value={form.type} onChange={(e) => set("type", e.target.value)}>{["ONBOARDING", "FEATURE_UPDATE", "REFRESHER", "CUSTOM"].map((x) => <option key={x} value={x}>{t(`trainingType.${x}`)}</option>)}</select><Input placeholder={t("field.subject")} value={form.title} onChange={(e) => set("title", e.target.value)} /><Input placeholder={t("field.location")} value={form.location} onChange={(e) => set("location", e.target.value)} /><Input type="date" value={form.scheduled_date} onChange={(e) => set("scheduled_date", e.target.value)} /><Input type="time" value={form.scheduled_time} onChange={(e) => set("scheduled_time", e.target.value)} /><Input type="number" step="0.5" value={form.duration_hours} onChange={(e) => set("duration_hours", e.target.value)} /><Input type="number" min="0" placeholder={t("field.attendees")} value={form.attendee_count} onChange={(e) => set("attendee_count", Number(e.target.value))} /><Textarea className="sm:col-span-2" placeholder={t("field.content")} value={form.description} onChange={(e) => set("description", e.target.value)} /></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.company || !form.title || !form.description || !form.scheduled_date || !form.location || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>;
}

function TrainingStatusDialog({ row, onClose, onSaved }: { row: CustomerTraining; onClose: () => void; onSaved: () => void }) { const t = useTranslations("adminCustomerService"); const [status, setStatus] = useState<TrainingStatus>(row.status); const [feedback, setFeedback] = useState(row.feedback); const save = useMutation({ mutationFn: () => updateTrainingStatus(row.id, status, feedback), onSuccess: () => { onSaved(); onClose(); } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.updateStatus")}</DialogTitle><DialogDescription>{row.training_code} / {row.title}</DialogDescription></DialogHeader><select className="h-8 rounded-md border bg-background px-2" value={status} onChange={(e) => setStatus(e.target.value as TrainingStatus)}>{["SCHEDULED", "COMPLETED", "CANCELLED"].map((x) => <option key={x} value={x}>{t(`trainingStatus.${x}`)}</option>)}</select><Textarea placeholder={t("field.feedback")} value={feedback} onChange={(e) => setFeedback(e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>; }

function VisitPanel() {
  const t = useTranslations("adminCustomerService"); const df = useDateFormat(); const qc = useQueryClient(); const companies = useCompanyOptions(); const rows = useQuery({ queryKey: ["customer-visits"], queryFn: () => getVisits({ page_size: 200 }) }); const [creating, setCreating] = useState(false);
  return <Panel loading={rows.isLoading} error={rows.isError}><div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.addVisit")}</Button></div><Table><TableHeader><TableRow>{["code", "company", "date", "visitor", "purpose", "feedback", "improvement"].map((key) => <TableHead key={key}>{t(`column.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.visit_code}</TableCell><TableCell>{row.company_name}</TableCell><TableCell>{df.date(row.visit_date)}</TableCell><TableCell>{row.visited_by_name || "-"}</TableCell><TableCell>{row.purpose}</TableCell><TableCell className="max-w-64">{row.summary || "-"}</TableCell><TableCell className="max-w-64">{row.action_items || "-"}</TableCell></TableRow>)}</TableBody></Table>{creating && <VisitDialog companies={companies.data?.results ?? []} onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-visits"] })} />}</Panel>;
}

function VisitDialog({ companies, onClose, onSaved }: { companies: CompanyRow[]; onClose: () => void; onSaved: () => void }) { const t = useTranslations("adminCustomerService"); const [form, setForm] = useState<VisitPayload>({ company: "", type: "FOLLOW_UP", visit_date: "", purpose: "", objectives: "", contact_met: "", summary: "", action_items: "", follow_up_required: false }); const set = (key: keyof VisitPayload, value: unknown) => setForm((x) => ({ ...x, [key]: value })); const save = useMutation({ mutationFn: () => createVisit(form), onSuccess: () => { onSaved(); onClose(); } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{t("action.addVisit")}</DialogTitle><DialogDescription>{t("dialog.visit")}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><CompanySelect companies={companies} value={form.company} onChange={(x) => set("company", x)} /><Input type="date" value={form.visit_date} onChange={(e) => set("visit_date", e.target.value)} /><Input placeholder={t("field.contactMet")} value={form.contact_met} onChange={(e) => set("contact_met", e.target.value)} /><Input placeholder={t("field.purpose")} value={form.purpose} onChange={(e) => set("purpose", e.target.value)} /><Textarea placeholder={t("field.objectives")} value={form.objectives} onChange={(e) => set("objectives", e.target.value)} /><Textarea placeholder={t("field.feedback")} value={form.summary} onChange={(e) => set("summary", e.target.value)} /><Textarea className="sm:col-span-2" placeholder={t("field.improvement")} value={form.action_items} onChange={(e) => set("action_items", e.target.value)} /><label className="flex items-center gap-2"><Switch checked={form.follow_up_required} onCheckedChange={(x) => set("follow_up_required", x)} />{t("field.followUp")}</label></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.company || !form.visit_date || !form.contact_met || !form.purpose || !form.objectives || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>; }

function FeedbackPanel() {
  const t = useTranslations("adminCustomerService"); const df = useDateFormat(); const qc = useQueryClient(); const companies = useCompanyOptions(); const rows = useQuery({ queryKey: ["customer-feedback"], queryFn: () => getFeedback({ page_size: 200 }) }); const [creating, setCreating] = useState(false); const [responding, setResponding] = useState<CustomerFeedback | null>(null);
  return <Panel loading={rows.isLoading} error={rows.isError}><div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.addFeedback")}</Button></div><Table><TableHeader><TableRow>{["code", "company", "category", "subject", "priority", "date", "status", "actions"].map((key) => <TableHead key={key}>{t(`column.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.feedback_code}</TableCell><TableCell>{row.company_name}</TableCell><TableCell>{t(`feedbackCategory.${row.category}`)}</TableCell><TableCell>{row.title}</TableCell><TableCell>{t(`priority.${row.priority}`)}</TableCell><TableCell>{df.date(row.created_at)}</TableCell><TableCell><StatusBadge label={t(row.is_resolved ? "status.resolved" : "status.open")} tone={row.is_resolved ? "positive" : "warning"} /></TableCell><TableCell><Button size="sm" variant="outline" onClick={() => setResponding(row)}><MessageSquareReply />{t("action.respond")}</Button></TableCell></TableRow>)}</TableBody></Table>{creating && <FeedbackDialog companies={companies.data?.results ?? []} onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-feedback"] })} />}{responding && <FeedbackResponseDialog row={responding} onClose={() => setResponding(null)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-feedback"] })} />}</Panel>;
}

function FeedbackDialog({ companies, onClose, onSaved }: { companies: CompanyRow[]; onClose: () => void; onSaved: () => void }) { const t = useTranslations("adminCustomerService"); const [form, setForm] = useState<FeedbackPayload>({ company: "", category: "FEATURE_REQUEST", title: "", description: "", priority: "MEDIUM" }); const set = (key: keyof FeedbackPayload, value: string) => setForm((x) => ({ ...x, [key]: value })); const save = useMutation({ mutationFn: () => createFeedback(form), onSuccess: () => { onSaved(); onClose(); } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.addFeedback")}</DialogTitle><DialogDescription>{t("dialog.feedback")}</DialogDescription></DialogHeader><CompanySelect companies={companies} value={form.company} onChange={(x) => set("company", x)} /><select className="h-8 rounded-md border bg-background px-2" value={form.category} onChange={(e) => set("category", e.target.value)}>{["FEATURE_REQUEST", "IMPROVEMENT", "BUG_REPORT", "COMPLAINT", "COMPLIMENT", "OTHER"].map((x) => <option key={x} value={x}>{t(`feedbackCategory.${x}`)}</option>)}</select><select className="h-8 rounded-md border bg-background px-2" value={form.priority} onChange={(e) => set("priority", e.target.value)}>{["LOW", "MEDIUM", "HIGH"].map((x) => <option key={x} value={x}>{t(`priority.${x}`)}</option>)}</select><Input placeholder={t("field.subject")} value={form.title} onChange={(e) => set("title", e.target.value)} /><Textarea placeholder={t("field.content")} value={form.description} onChange={(e) => set("description", e.target.value)} /><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.company || !form.title || !form.description || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>; }

function FeedbackResponseDialog({ row, onClose, onSaved }: { row: CustomerFeedback; onClose: () => void; onSaved: () => void }) { const t = useTranslations("adminCustomerService"); const [response, setResponse] = useState(row.response); const [resolved, setResolved] = useState(row.is_resolved); const save = useMutation({ mutationFn: () => respondFeedback(row.id, response, resolved), onSuccess: () => { onSaved(); onClose(); } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{t("action.respond")}</DialogTitle><DialogDescription>{row.feedback_code} / {row.title}</DialogDescription></DialogHeader><p className="text-sm text-muted-foreground">{row.description}</p><Textarea placeholder={t("field.response")} value={response} onChange={(e) => setResponse(e.target.value)} /><label className="flex items-center gap-2"><Switch checked={resolved} onCheckedChange={setResolved} />{t("status.resolved")}</label><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!response.trim() || save.isPending} onClick={() => save.mutate()}><Check />{t("action.confirm")}</Button></DialogFooter></DialogContent></Dialog>; }

function ServicePanel() {
  const t = useTranslations("adminCustomerService"); const df = useDateFormat(); const qc = useQueryClient(); const companies = useCompanyOptions(); const rows = useQuery({ queryKey: ["customer-service-records"], queryFn: () => getServiceRecords({ page_size: 200 }) }); const [creating, setCreating] = useState(false);
  return <Panel loading={rows.isLoading} error={rows.isError}><div className="flex justify-end border-b p-3"><Button onClick={() => setCreating(true)}><Plus />{t("action.addService")}</Button></div><Table><TableHeader><TableRow>{["code", "company", "date", "type", "subject", "handler", "resolution", "satisfaction"].map((key) => <TableHead key={key}>{t(`column.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{(rows.data?.results ?? []).map((row) => <TableRow key={row.id}><TableCell>{row.service_code}</TableCell><TableCell>{row.company_name}</TableCell><TableCell>{df.date(row.service_date)}</TableCell><TableCell>{t(`serviceType.${row.type}`)}</TableCell><TableCell>{row.subject}</TableCell><TableCell>{row.handled_by_name || "-"}</TableCell><TableCell className="max-w-64">{row.resolution || "-"}</TableCell><TableCell>{row.customer_satisfied === null ? t("status.notRated") : row.customer_satisfied ? t("status.satisfied") : t("status.unsatisfied")}</TableCell></TableRow>)}</TableBody></Table>{creating && <ServiceDialog companies={companies.data?.results ?? []} onClose={() => setCreating(false)} onSaved={() => qc.invalidateQueries({ queryKey: ["customer-service-records"] })} />}</Panel>;
}

function ServiceDialog({ companies, onClose, onSaved }: { companies: CompanyRow[]; onClose: () => void; onSaved: () => void }) { const t = useTranslations("adminCustomerService"); const [form, setForm] = useState<ServiceRecordPayload>({ company: "", type: "CONSULTATION", service_date: "", contact_person: "", subject: "", description: "", resolution: "", customer_satisfied: null }); const set = (key: keyof ServiceRecordPayload, value: unknown) => setForm((x) => ({ ...x, [key]: value })); const save = useMutation({ mutationFn: () => createServiceRecord(form), onSuccess: () => { onSaved(); onClose(); } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{t("action.addService")}</DialogTitle><DialogDescription>{t("dialog.service")}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><CompanySelect companies={companies} value={form.company} onChange={(x) => set("company", x)} /><Input type="date" value={form.service_date} onChange={(e) => set("service_date", e.target.value)} /><select className="h-8 rounded-md border bg-background px-2" value={form.type} onChange={(e) => set("type", e.target.value)}>{["CONSULTATION", "ISSUE_RESOLUTION", "CUSTOMIZATION", "INTEGRATION", "GENERAL_SUPPORT"].map((x) => <option key={x} value={x}>{t(`serviceType.${x}`)}</option>)}</select><Input placeholder={t("field.contactPerson")} value={form.contact_person} onChange={(e) => set("contact_person", e.target.value)} /><Input className="sm:col-span-2" placeholder={t("field.subject")} value={form.subject} onChange={(e) => set("subject", e.target.value)} /><Textarea placeholder={t("field.content")} value={form.description} onChange={(e) => set("description", e.target.value)} /><Textarea placeholder={t("field.resolution")} value={form.resolution} onChange={(e) => set("resolution", e.target.value)} /><select className="h-8 rounded-md border bg-background px-2" value={form.customer_satisfied === null ? "" : String(form.customer_satisfied)} onChange={(e) => set("customer_satisfied", e.target.value === "" ? null : e.target.value === "true")}><option value="">{t("status.notRated")}</option><option value="true">{t("status.satisfied")}</option><option value="false">{t("status.unsatisfied")}</option></select></div><DialogFooter><Button variant="outline" onClick={onClose}>{t("action.cancel")}</Button><Button disabled={!form.company || !form.service_date || !form.contact_person || !form.subject || !form.description || save.isPending} onClick={() => save.mutate()}><Save />{t("action.save")}</Button></DialogFooter></DialogContent></Dialog>; }

function ReportPanel() {
  const t = useTranslations("adminCustomerService"); const summary = useQuery({ queryKey: ["customer-service-summary"], queryFn: getCustomerServiceSummary });
  const reports = [
    ["customers", ["code", "name", "type", "contact_person", "contact_phone", "contact_email", "status", "state"]],
    ["enquiries", ["enquiry_code", "company_name", "contact_person", "contact_phone", "subject", "status", "assigned_to_name", "created_at"]],
    ["training", ["training_code", "company_name", "type", "title", "scheduled_date", "trainer_name", "attendee_count", "status"]],
    ["visits", ["visit_code", "company_name", "visit_date", "purpose", "visited_by_name", "summary", "action_items"]],
    ["feedback", ["feedback_code", "company_name", "category", "title", "priority", "is_resolved", "response", "created_at"]],
    ["service", ["service_code", "company_name", "type", "service_date", "subject", "handled_by_name", "resolution", "customer_satisfied"]],
  ] as const;
  const exporting = useMutation({ mutationFn: ({ dataset, format, fields }: { dataset: string; format: "pdf" | "xlsx"; fields: readonly string[] }) => exportCustomerServiceReport(dataset, format, t(`report.${dataset}`), fields.map((key) => ({ key, label: t(`exportColumn.${key}`) }))) });
  return <div className="min-h-0 flex-1 overflow-y-auto rounded-lg border bg-card shadow-sm"><div className="grid border-b sm:grid-cols-2 xl:grid-cols-4">{[["customers", summary.data?.customers ?? 0], ["service", summary.data?.service_records ?? 0], ["feedback", summary.data?.feedback ?? 0], ["completion", `${summary.data?.completion_rate ?? 0}%`]].map(([key, value]) => <div key={key} className="border-b border-r p-4"><p className="text-xs text-muted-foreground">{t(`metric.${key}`)}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div><div className="divide-y">{reports.map(([dataset, fields]) => <div key={dataset} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"><div><p className="font-medium">{t(`report.${dataset}`)}</p><p className="text-xs text-muted-foreground">{t(`report.${dataset}Subtitle`)}</p></div><div className="flex gap-2"><Button variant="outline" disabled={exporting.isPending} onClick={() => exporting.mutate({ dataset, format: "pdf", fields })}><FileDown />PDF</Button><Button disabled={exporting.isPending} onClick={() => exporting.mutate({ dataset, format: "xlsx", fields })}><FileDown />Excel</Button></div></div>)}</div></div>;
}
